### ISSUE TITLE
lambda_execute should cope with list as payload (instead of dict)

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible-collections/amazon.aws#1082]
##### SUMMARY

AWS Lambda functions are able to process input arguments which are a list, not a dictionary.

Ansible's `execute_lambda` is not able to.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

execute_lambda

##### ANSIBLE VERSION

```
ansible 2.9.0
  config file = /home/ec2-user/.ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.6.10 (default, Feb 10 2020, 19:55:14) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/ec2-user/.ansible.cfg) = True
DEFAULT_LOCAL_TMP(/home/ec2-user/.ansible.cfg) = /dev/shm/ansible/tmp_local/ansible-local-71308po4z6ow
```

##### OS / ENVIRONMENT

Amazon Linux

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  connection: local

  vars:
    payload:
     - abc
     - 123
    arn: "arn:aws:lambda:ap-southeast-2:123:function:empty" # TODO: change for your case
    region: "ap-southeast-2"

  tasks:
    - name: invoke using cli
      shell: >
        aws lambda invoke
        --function-name {{ arn }}
        --invocation-type RequestResponse
        --payload '{{ payload | to_json }}'
        /tmp/result
    - name: through Ansible module
      execute_lambda:
        function_arn: "{{ arn }}"
        region: "{{ region }}"
        wait: yes
        tail_log: yes
        payload: "{{ payload }}"
  
```

Where `arn` is the arn of a Lambda with body:

```
def lambda_handler(event, context):
    return event
```
This example invokes the Lambda from the cli (which works),
then tries to do the same thing from `execute_lambda`, which doesn't work.

##### EXPECTED RESULTS

The playbook should run without error

##### ACTUAL RESULTS

```
TASK [through Ansible module] **********************************************************************************************************************
custom filter file loaded
fatal: [localhost]: FAILED! => {"changed": false, "msg": "argument payload is of type <class 'list'> and we were unable to convert to dict: <class 'list'> cannot be converted to a dict"}
```
