### ISSUE TITLE
rds_snapshot module currently does not support sharing the snapshot with other aws accounts

### ISSUE THREAD

**Issue by emanuele-leopardi** [ansible-collections/amazon.aws#1084]
### Summary

I'm trying to share an rds db snapshot with another account but it seems this feature is not available right now.

Also I just noticed there is no way to copy the snapshot with a different KMS key , to decrypt and re-encrypt the new snap , not sure this goes into this module or another one (something like [ec2_ami_copy](https://docs.ansible.com/ansible/latest/collections/community/aws/ec2_ami_copy_module.html) for rds)

### Issue Type

Feature Idea

### Component Name

rds_snapshot

### Additional Information

```yaml (paste below)
community.aws.rds_snapshot:
    db_instance_identifier: "{{ db.name }}"
    db_snapshot_identifier: "{{ db.name }}-{{ ansible_date_time.date }}"
    launch_permissions: # same as amazon.aws.ec2_ami module
      user_ids: "{{ account_ids }}" # as a list
    wait: true   
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
