### ISSUE TITLE
ec2_instance - unable to start instances by tag.

### ISSUE THREAD

**Issue by leosimony** [ansible-collections/amazon.aws#1126]
### Summary

When I try to start an EC2 instance using tags via ansible-playbook, it's throwing the below error message. If I add image_id then its launching a new instance rather than starting the existing one.

You must include an image_id or image.id parameter to create an instance or use a launch_template.

### Issue Type

Bug Report

### Component Name

amazon.aws.ec2_instance

### Ansible Version

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/leosimon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
```
### Collection Versions

```
amazon.aws v2.0.0
```

Tried the latest version 5.0.0 - same issue

### AWS SDK versions

```
leosimon@ansible-awx:~$ pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires:
Required-by:
---
Name: boto3
Version: 1.18.40
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /home/leosimon/.local/lib/python3.8/site-packages
Requires: botocore, jmespath, s3transfer
Required-by:
---
Name: botocore
Version: 1.27.67
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: boto3, s3transfer
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 20.04.5 LTS \n \l

### Steps to Reproduce

```
---
- name: Start or Stop EC2 instances based on Tag information
  hosts: localhost
  gather_facts: false
  vars:
    - group: tag_name
    - instance_stop: false
    - instance_start: true
    - add_to_checkmk: false
    - region: us-east-1
    - hostnames: "{{ tags.Name }}"
    - ipaddress: "{{ public_ip_address }}"
  tasks:
    - name: Start the EC2 instance in us-east-1 region
      amazon.aws.ec2_instance:
        profile: devops-profile
        region: us-east-1
        tags:
          Type: "{{ group }}"
        state: started
        wait: true
      register: ec2_east
      when:
        - instance_start
        - region == "us-east-1"

```

### Expected Results

The EC2 instances which match the tag value should get started. 

### Actual Results

You must include an image_id or image.id parameter to create an instance or use a launch_template

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by goneri** [comment]
Hi @leosimony, Can you try to pass the instance ID through the `instance_ids` parameter?

**Comment by leosimony** [comment]
@goneri If we pass instance_ids it is working as expected.  This seems to be a problem with the module 'amazon.aws.ec2_instance' that comes from amazon.aws collections. There are changes in this module that needed to be updated in the task and did as well. For ex: 'instance_tags' is changed as 'tags'. The module comes from the collections that have advanced use cases is great but a feature that worked earlier stopped working or changing its behavior is kind of worrying. This becomes more difficult while using AWX Kubernetes setup with the latest execution environment.

I was using the ec2 module earlier with the below task. The Ansible version is 2.9.x and the module comes as default and not under collections. This task starts all the EC2 instances that match the tag key 'Type' and value passed via variable "group". 

```
    - name: Start the EC2 instance in the us-east-1 region
      ec2:
        profile: "{{ aws_profile }}"
        region: us-east-1
        instance_tags:
          Type: "{{ group }}"
        state: running
        wait: true
      register: ec2_east
      when:
        - instance_start
        - region == "us-east-1"
```
Please let me know if you need more information.

**Comment by tremble** [comment]
> The module comes from the collections that have advanced use cases is great but a feature that worked earlier stopped working or changing its behavior is kind of worrying

In general we try to avoid breaking behavior, and new modules come with integration tests which help to avoid this.  Ironically, `ec2` being one of the oldest modules had almost no integration tests.

However, the `ec2_instance` module is a separate module, originally released over 4 years ago (Ansible 2.5).  The two modules had been available in parallel until we dropped `ec2` with amazon.aws 4.0.0 in June of this year because the original SDK (`boto`) that it was based upon was abandoned by Amazon in favor of the SDK that`ec2_instance` is based upon (`boto3`/`botocore`) .  Unfortunately the two SDKs functioned very differently and because of the differences in how the SDKs work the modules also behaved subtly differently.  Unfortunately folks tended to use either one or the other, so missing features went unnoticed until "something" would break with the old SDK for them (usually authentication related).

As a temporary solution `amazon.aws.ec2` is still available in the 3.5.0 release (the final planned release in the 3.x series), which was released last week, it should be possible to pin the amazon.aws collection you're using to 3.5.0.

**Comment by leosimony** [comment]
@tremble Thanks for explaining. Will try with 3.5.0 and update you if any issues. 
The behavior of starting instances with tags will be included in the latest version of collections? or its a collaborative work?

**Comment by tremble** [comment]
> The behavior of starting instances with tags will be included in the latest version of collections? or its a collaborative work?

 Someone will need to write the code, I don't know how involved the change would be, but it's definitely a reasonable change to make

**Comment by tremble** [comment]
@leosimony I've just dug a little further into the code:

It should be possible to achieve what you want using `ec2_instance`.  However, the syntax is different

https://ansible-collections.github.io/amazon.aws/branch/main/collections/amazon/aws/ec2_instance_module.html#parameter-filters

> filters
> A dict of filters to apply when deciding whether existing instances match and should be altered. Each dict item consists of a filter key and a filter value. See https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html. for possible filters. Filter names and values are case sensitive.
>
> By default, instances are filtered for counting by their “Name” tag, base AMI, state (running, by default), and subnet ID. Any queryable filter can be used. Good candidates are specific tags, SSH keys, or security groups.


An example that we use in our integration tests:
```
  - name: "Terminate the instance"
    ec2_instance:
      state: absent
      filters:
        "tag:TestId": "{{ ec2_instance_tag_TestId }}"
      wait: yes 
    ignore_errors: yes 
```

When using this to start instances you may still get a (spurious) deprecation warning about the default instance type going away, however it should be possible to start your instances using:

```
  - name: "Start the group instances"
    ec2_instance:
      state: started
      wait: True
      filters:
        "tag:Type": "{{ group }}"
```
