### ISSUE TITLE
route53_health_check - no "health_check" information returned when updating 

### ISSUE THREAD

**Issue by anjo-swe** [ansible-collections/amazon.aws#1190]
### Summary

When updating a Route53 health check the only information returned is that it was changed

One suggestion is to update `update_health_check` so it returns `check_id` in all 3 spots (need to move `check_id = existing_check.get('Id')` further up in the method)
https://github.com/ansible-collections/amazon.aws/blob/f9751fab28c55d793df7996f599839a3ace5414b/plugins/modules/route53_health_check.py#L472

Only happens when the following snippet doesn't find an existing health check
https://github.com/ansible-collections/amazon.aws/blob/f9751fab28c55d793df7996f599839a3ace5414b/plugins/modules/route53_health_check.py#L592

### Issue Type

Bug Report

### Component Name

route53_health_check

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.12.2]
  config file = /Users/<USER>/Source/dataintelligence-ansible/ansible.cfg
  configured module search path = ['/Users/<USER>/Source/dataintelligence-ansible/library']
  ansible python module location = /Users/<USER>/Source/dataintelligence-ansible/.runtime/.pyvenv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/<USER>/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/<USER>/Source/dataintelligence-ansible/.runtime/.pyvenv/bin/ansible
  python version = 3.9.8 (main, Nov 18 2021, 16:08:04) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 2.11.3
  libyaml = True
```

### Collection Versions

Manually added https://github.com/ansible-collections/amazon.aws/blob/5.0.2/plugins/modules/route53_health_check.py to my local Ansible

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore

Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /Users/<USER>/Source/dataintelligence-ansible/.runtime/.pyvenv/lib/python3.9/site-packages
Requires:
Required-by:
---
Name: boto3
Version: 1.20.48
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /Users/<USER>/Source/dataintelligence-ansible/.runtime/.pyvenv/lib/python3.9/site-packages
Requires: botocore, jmespath, s3transfer
Required-by: aws-sam-cli, aws-sam-translator, serverlessrepo
---
Name: botocore
Version: 1.23.48
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /Users/<USER>/Source/dataintelligence-ansible/.runtime/.pyvenv/lib/python3.9/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: awscli, boto3, s3transfer
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

macOS 11.6

### Steps to Reproduce

Run the following playbook twice (change `fqdn` to a new value before the 2nd run)

```yaml (paste below)
---
- hosts: localhost
  tasks:
    - name: Create a health-check
      route53_health_check:
        health_check_name: my-health-check
        use_unique_names: true
        fqdn: ***
        type: HTTPS
        resource_path: /
        request_interval: 30
        failure_threshold: 3
        tags:
          Service: my-service
          Owner: some-owner
          Lifecycle: dev
      register: my_health_check
```

#### First Run (create)

```yaml (paste below)
changed: [localhost] => changed=true
  health_check:
    action: create
    caller_reference: ***
    health_check_config:
      ...
```

#### Second Run (update)

```yaml (paste below)
changed: [localhost] => changed=true
  health_check:
    action: update
    caller_reference: ***
    health_check_config:
      ...
```

#### First Run (create)

```yaml (paste below)
changed: [localhost] => changed=true
  health_check:
    action: create
    caller_reference: ***
    health_check_config:
      ...
```

#### Second Run (update, no `health_check_config` returned)

```yaml (paste below)
changed: [localhost] => changed=true
  health_check:
    action: update
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
