### ISSUE TITLE
aws_ssm lookup does not fail when parameter does not exist

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/amazon.aws#126]
_From @tinyzimmer on Jan 02, 2019 20:09_

##### SUMMARY

Using the `aws_ssm` lookup plugin to fetch an application secret, if the parameter does not exist, the plugin will fail silently setting an empty string for the queried `value`.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

`aws_ssm`

##### ANSIBLE VERSION

2.7.5

##### CONFIGURATION

```
user@somecomputer /cygdrive/c/Users/{{ redacted }}/Development/{{ redacted }}
$ ansible-config dump --only-changed

user@somecomputer /cygdrive/c/Users/{{ redacted }}/Development/{{ redacted }}
$
```

##### OS / ENVIRONMENT

Running in Cygwin on Windows 10 Pro (work computer 🤢) but likely affects other platforms?

##### STEPS TO REPRODUCE

```yaml
# test.yml
- name: Test Param Retrieval
  hosts: localhost
  gather_facts: false
  tasks:

    # I'd expect this to fail
    - set_fact:
        test_var: "{{ lookup('aws_ssm', 'nonexistant_param', region='us-east-1') }}"

    - debug:
        var: test_var
```

##### EXPECTED RESULTS

Fail because of non-existent parameter. Since it wasn't failing, I had no idea I was using the wrong AWS Shared Credentials Profile on the computer I was running this from. If this is expected behavior I suppose that's fine, but I don't see why it would be.

##### ACTUAL RESULTS

Playbook continues and any templates that use that value set it to an empty string

```bash
$ ansible-playbook test.yml
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'


PLAY [Test Param Retrieval] ****************************************************

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "test_var": ""
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

_Copied from original issue: ansible/ansible#50466_

**Comment by Akasurde** [comment]
_From @Edward-Ireson on Nov 19, 2019 16:32_

I had the same issue and had to work around it, I did 

"{{ lookup('aws_ssm', '/var/var1', region='eu-west-2', shortnames=true ) | default(NULL,true) }}"

The lookup is passed an empty result which because of the true flag tries to set the default to NULL which then fails because NULL is not defined.

**Comment by ansibullbot** [comment]
cc @jillr @lwade @s-hertel @tremble @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by markuman** [comment]
it looks like that this behaviour is by design.  

- https://github.com/ansible-collections/amazon.aws/blob/main/plugins/lookup/aws_ssm.py#L214
- https://github.com/ansible-collections/amazon.aws/blob/main/plugins/lookup/aws_ssm.py#L228

Furthermore, the documentation mentioned this behaviour also.

> If looking up an explicitly listed parameter by name which does not exist then the lookup will return a None value which will be interpreted by Jinja2 as an empty string. You can use the `default` filter to give a default value in this case but must set the second parameter to true (see examples below)

https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ssm_lookup.html

**Comment by JonTheNiceGuy** [comment]
> 
> 
> _From @Edward-Ireson on Nov 19, 2019 16:32_
> 
> I had the same issue and had to work around it, I did
> 
> "{{ lookup('aws_ssm', '/var/var1', region='eu-west-2', shortnames=true ) | default(NULL,true) }}"
> 
> The lookup is passed an empty result which because of the true flag tries to set the default to NULL which then fails because NULL is not defined.

NULL isn't defined. You're probably want something like this:

```yaml
- name: Test Param Retrieval
  hosts: localhost
  gather_facts: false
  tasks:
    - set_fact:
        test_var: "{{ lookup('aws_ssm', 'nonexistant_param', region='us-east-1') }}"

    - fail:
        when: test_var == ''
```

or


```yaml
- name: Test Param Retrieval
  hosts: localhost
  gather_facts: false
  tasks:
    - fail:
      when: lookup('aws_ssm', 'nonexistant_param', region='us-east-1') == ''

    - set_fact:
        test_var: "{{ lookup('aws_ssm', 'nonexistant_param', region='us-east-1') }}"
```
I don't believe any lookup will cause a "fail" state to occur.
