### ISSUE TITLE
lambda integration tests - potential test flake

### ISSUE THREAD

**Issue by tremble** [ansible-collections/amazon.aws#1277]
Another issue I just found: **[lambda]** Integration tests fail if the account is not empty. The lambda integration tests assume there are no other lambdas in the account. I just swapped my region to one I don't use. 

The error was for integration testing lambda. It was an assertion error.

```
  - name: lambda_info | Ensure default query value is 'config' when function name
      omitted
    lambda_info:
    register: lambda_infos_query_config
    check_mode: yes
  - name: lambda_info | Assert successfull retrieval of all information
    assert:
      that:
...
      - lambda_infos_query_config.functions[0].function_name == lambda_function_name
      - 
```

If the freshly created lambda for this test is not the first lambda in the list (because a pre-existing lambda is), then this assertion fails.

Perhaps it's just that this specific test needs to be made a bit smarter.

_Originally posted by @mdavis-xyz in https://github.com/ansible-collections/amazon.aws/issues/924#issuecomment-1319708366_

### Issue Type

Bug Report

### Component Name

lambda

### Ansible Version

CI / latest

### Collection Versions

CI / latest

### Configuration

CI

### OS / Environment

CI

### Steps to Reproduce

Run lambda integration tests in an account with existing lambda

### Expected Results

Run without errors

### Actual Results

Assertion failure

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
