### ISSUE TITLE
get_aws_connection_info: Explicitly specified credentials are overridden by the profile with boto3

### ISSUE THREAD

**Issue by abadger** [ansible-collections/amazon.aws#130]
##### SUMMARY
I was looking at the code in ```get_aws_connection_info``` https://github.com/ansible-collections/amazon.aws/blob/main/plugins/module_utils/ec2.py#L331 and think I found a bug with profile and other credentials.

If the user explicitly specifies both profile and other credentials (like security_token) in the playbook, profile silently overrides any of the given credentials.  This is undesirable as the user has the most control over the playbook parameters so playbook parameters should either take precedence over profile or these playbook parameters should be mutually_exclusive with the profile.

I also see that the profile is being retrieved from environment variables if the profile_name is not set.  That will have to be rethought in this case too.... Perhaps implementing the playbook parameters overriding the profile is the only way to make this work.
 
Precedence of values should be (earliest entry should override anything later):
* Explicitly specified via a playbook parameter
* Part of the profile explicitly specified via a playbook parameter
* Part of the profile specified by env vars on the target machine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/module_utils/ec2.py

##### ANSIBLE VERSION

```paste below
devel
```

This exists on 2.8 as well but I'm not sure if it should be backported as it is a new deprecation.

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by tremble** [comment]
@abadger @jillr @s-hertel :

Given that this would be a fairly substantial change my feeling is that we take the opportunity to massively simplify the logic:

1. Add a lookup plugin for querying boto.config and boto3.config
2. Deprecate using os.environ as a source of credentials **entirely**, recommending that folks use lookup('env') if they need to simulate the current behaviour
3. Deprecate the passing of both a profile and credentials at the same time as each other (preparing to make them mutually exclusive)

Thoughts?  Objections?

**Comment by tremble** [comment]
It's been pointed out that using ENV variables helps for general use, I think if we continue to use them there needs to be an easy to describe way of saying "Read everything from Profile" "Read everything from ENV" "Read everything from creds parameters", right now it's easy to end up with an ugly mix.

**Comment by flowerysong** [comment]
@tremble Bear in mind that lookups are not a direct replacement for the usage of environment variables or boto configuration, because they run on the controller instead of the target host.

E.g. the following playbook:
```
 hosts: mighty-hossu.mx.x.mail.umich.edu
  become: false
  tasks:
    - name: This uses the secrets from the environment on the target
      aws_s3_sync:
        direction: pull
        bucket: "{{ yum_hostname }}"
        region: "{{ yum_aws_region }}"
        prefix: "{{ yum_repo_path }}"
        path: /var/tmp/yum

    - name: This uses the secrets from the environment on the controller, which don't work
      aws_s3_sync:
        direction: pull
        bucket: "{{ yum_hostname }}"
        region: "{{ yum_aws_region }}"
        prefix: "{{ yum_repo_path }}"
        path: /var/tmp/yum
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
```

Results in this:
```
TASK [Gathering Facts] *********************************************************
ok: [mighty-hossu.mx.x.mail.umich.edu]

TASK [This uses the secrets from the environment on the target] ****************
ok: [mighty-hossu.mx.x.mail.umich.edu]

TASK [This uses the secrets from the environment on the controller, which don't work] ***
An exception occurred during task execution. To see the full traceback, use -vvv
. The error was: ClientError: An error occurred (SignatureDoesNotMatch) when cal
ling the ListObjectsV2 operation: The request signature we calculated does not m
atch the signature you provided. Check your key and signing method.
[...]
```
