### ISSUE TITLE
S3 bucket create using profile parameter with other provider

### ISSUE THREAD

**Issue by eliteaz** [ansible-collections/amazon.aws#1301]
### Summary

with such a simple task:
```
- name: Create  S3 bucket
  delegate_to: localhost
  s3_bucket:
    name: "{{ item.name }}"
    endpoint_url: "https://s3.eu-central-1.wasabisys.com"
    profile: "wasabi"
    region: "{{ item.region }}"
  with_items: "{{ s3_bucket }}"
```
get an err `Failed to check bucket presence: An error occurred (403) when calling the HeadBucket operation: Forbidden`

after removing `profile_name` from 
https://github.com/ansible-collections/amazon.aws/blob/main/plugins/modules/s3_bucket.py#L1160
bucket is created as well

seems like using `profile` parameter there is additional `HEAD` header checking.
otherwise than using module `access_key` and `secret_key` parameters

### Issue Type

Bug Report

### Component Name

s3_object, s3_bucket

### Ansible Version

```
ansible [core 2.12.5]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.11.3
  libyaml = True
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
amazon.aws           5.1.0
community.aws        5.0.0
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Name: boto3
Version: 1.26.30
Name: botocore
Version: 1.29.30

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
- name: Create  S3 bucket
  delegate_to: localhost
  s3_bucket:
    name: "{{ item.name }}"
    endpoint_url: "https://s3.eu-central-1.wasabisys.com"
    profile: "wasabi"
    region: "{{ item.region }}"
  with_items: "{{ s3_bucket }}"
```

### Expected Results

I expect bucket create using `profile` parameter

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
