### ISSUE TITLE
ec2_instance: Add support to run spot instances

### ISSUE THREAD

**Issue by tgadiev** [ansible-collections/amazon.aws#1338]
### Summary

It looks like this module lacks this useful ability and it's even mentioned in documentation. There's recommendation to use `ec2_spot_instance` module. Unfortunately, `ec2_spot_instance` module does not support setting instance metadata option, which is highly needed in some cases. Thus we have a big gap in functionality. You have option to run spot instances using `ec2_spot_instance` but without adjusted metadata option, or you can run instances using `ec2_instance` module having this feature, but this way you cannot start spot instances. According to [boto documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.run_instances) adding spot support is quite simple - just need to add `InstanceMarketOptions` properties to `build_top_level_options` function. 

### Issue Type

Feature Idea

### Component Name

ec2_instance

### Additional Information

I would like to have it like this:

```yaml (paste below)
- name: start spot instance with metadata options
  amazon.aws.ec2_instance:
    name: "spot-metadataoptions-instance"
    vpc_subnet_id: subnet-5calable
    instance_type: t3.small
    image_id: ami-123456
    tags:
      Environment: Testing
    metadata_options:
      http_endpoint: enabled
      http_tokens: optional
    spot_options:
      spot_instance_type: 'one-time'
      max_price: '0.055' 
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
