### ISSUE TITLE
Multiple listener certificates for alb

### ISSUE THREAD

**Issue by omarqureshi** [ansible-collections/amazon.aws#1349]
### Summary

I am trying to add multiple certificates for a single load balancer, i.e. I'd like a load balancer that would be able to host sites that have the host name of foo.com and bar.com

In cloudformation, this can be done by using [AWS::ElasticLoadBalancingV2::ListenerCertificate](https://awstut.com/en/2022/02/19/attaching-multiple-acm-certificates-to-alb-to-support-multiple-domains-2/#toc9) and in boto3 this can be done with [add_listener_certificates()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elbv2.html#ElasticLoadBalancingv2.Client.add_listener_certificates)

### Issue Type

Feature Idea

### Component Name

amazon.aws.elb_application_lb_certificate

### Additional Information

```yaml
amazon.aws.elb_application_lb_certificate:
  listener: "{{ load_balancer.listeners[0].listener_arn }}"
  certificates:
    - CertificateArn: "{{ foo_certificate_arn }}"
      IsDefault: true
    - CertificateArn: "{{ bar_certificate_arn }}"
      IsDefault: false
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
