### ISSUE TITLE
Filters does not support AND logic of multiple tag-key values

### ISSUE THREAD

**Issue by viv-dev** [ansible-collections/amazon.aws#1354]
### Summary

It seems that there is no way to query ec2 instances via multiple tag-key filters that have AND logic since `filters` is a dict and `include_filters` treats all variations as OR conditions.

### Issue Type

Bug Report

### Component Name

amazon.aws.aws_ec2

### Ansible Version

```console
ansible [core 2.14.2]
```

### Collection Versions

```console
Collection Version
---------- -------
amazon.aws 5.1.0  
```

### AWS SDK versions

```console (paste below)
Name: boto3
Version: 1.26.60

Name: botocore
Version: 1.29.60
```

### Steps to Reproduce

```yaml
plugin: amazon.aws.aws_ec2

hostnames:
  - tag:Name

filters:
  # Applies as OR logic
  # Because filters is a dict can't specify multiple separate tag-key filters
  tag-key:
    - Role
    - Environment
```

```yaml
plugin: amazon.aws.aws_ec2

hostnames:
  - tag:Name

include_filters:
  # Applies as OR logic
  - tag-key: Role
  - tag-key: Environment

```

```yaml
plugin: amazon.aws.aws_ec2

hostnames:
  - tag:Name

include_filters:
  # Also applies as OR logic
  - tag-key: 
      - Role
      - Environment
```

### Expected Results

That there is a way to apply AND logic for multiple tag keys as per the aws command below:

```bash
aws ec2 describe-instances --filter Name=tag-key,Values=Role Name=tag-key,Values=Team
```

This is in line with the AWS documentation which says that multiple filters with the same name are treated with the AND condition:

https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html#options

### Actual Results

Both the `filters` version and `include_filters` return instances that have either the tag Role defined or Team defined, but not explicitly the ones that only have both.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
