### ISSUE TITLE
Allow recursive copy of objects in S3 bucket

### ISSUE THREAD

**Issue by jsabater** [ansible-collections/amazon.aws#1379]
### Summary

Implement recursive copy of all objects from (source) bucket to (destination) bucket and from local to bucket. Example on Amazon AWS:

`aws s3 cp localfolder s3://dstbucket/ --recursive`

Example using MinIO console client:

`mcli cp --recursive minio1/srcbucket/ minio1/dstbucket/`

Context: Right now, when a new website is created via a playbook, `srcbucket` contains the default list of objects (images) to be copied to the newly created bucket. For that I am executing the example above console command of  `mcli` because feeding the list of images taken using `s3_object` in list mode to `s3_object` in copy mode is just too slow.

### Issue Type

Feature Idea

### Component Name

amazon.aws.s3_object

### Additional Information

Using current examples from the [documenation](https://docs.ansible.com/ansible/latest/collections/amazon/aws/s3_object_module.html), a proposal could be as follows:

```yaml
- name: Copy all objects already stored in another bucket
  amazon.aws.s3_object:
    endpoint_url: <my-endpoint>
    access_key: <my-access-key>
    secret_key: <my-secret-key>
    bucket: dstbucket
    object: / # Or 'all' or something similar. Could even not be required given the value of 'copy_src.object' below
    mode: copy
    copy_src:
        bucket: srcbucket
        object: / # Or 'all' or something similar
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
