### ISSUE TITLE
ec2_instance - attach network interfaces issue when using check_mode

### ISSUE THREAD

**Issue by abikouo** [ansible-collections/amazon.aws#1403]
### Summary

When trying to attach a new network interface to a running instance with check_mode, the module performs the update instead of just validating if this will be done.

### Issue Type

Bug Report

### Component Name

ec2_instance

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  gather_facts: false

  collections:
    - amazon.aws
 
  vars:
    vpc_name: "aubin-test-ec2-0303-2"
    vpc_cidr: "10.1.0.0/16"
    subnet_cidr: "10.1.1.0/24"
    security_group_name: "aubin-test-sg-01"
    ec2_name: "aubin-0303-ec2"
    ec2_instance_type: "t3.nano"
    ec2_ami_id: "ami-0b1236a14f61e87b5"

  tasks:
    - name: "Create VPC for use in testing"
      ec2_vpc_net:
        state: present
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        tags:
          Name: "{{ vpc_name }}"
        tenancy: default
      register: testing_vpc

    - name: "Create default subnet"
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ testing_vpc.vpc.id }}"
        cidr: "{{ subnet_cidr }}"
      register: testing_subnet
    
    - name: "create a security group with the vpc"
      ec2_security_group:
        name: "{{ security_group_name }}"
        description: security group for ansible tests
        vpc_id: "{{ testing_vpc.vpc.id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: sg

    - name: create an Elastic network interface
      ec2_eni:
        state: present
        delete_on_termination: true
        subnet_id: "{{ testing_subnet.subnet.id }}"
        security_groups:
          - "{{ sg.group_id }}"
      register: enis
      with_items: "{{ range(2) }}"
    
    - name: Create instance
      ec2_instance:
        state: running
        name: "{{ ec2_name }}"
        image_id: "{{ ec2_ami_id }}"
        vpc_subnet_id: "{{ testing_subnet.subnet.id }}"
        instance_type: "{{ ec2_instance_type }}"
        network:
          interfaces:
            - id: "{{ enis.results.0.interface.id }}"
        wait: true
      register: create_instance
    
    - assert:
        that:
          - create_instance is changed
    
    - name: "Gather instance info"
      ec2_instance_info:
        filters:
          "tag:Name": "{{ ec2_name }}"
          instance-state-name: running
      register: _instances_info
    
    - assert:
        that:
          - _instances_info.instances | length == 1

    - name: Attach network interface(s) to the instance
      ec2_instance:
        state: running
        name: "{{ ec2_name }}"
        image_id: "{{ ec2_ami_id }}"
        vpc_subnet_id: "{{ testing_subnet.subnet.id }}"
        network:
          interfaces:
            - id: "{{ enis.results.0.interface.id }}"
            - id: "{{ enis.results.1.interface.id }}"
        instance_type: "{{ ec2_instance_type }}"
        wait: true
      register: create_with_eni
      check_mode: true
    
    - assert:
        that:
          - create_with_eni is changed
    
    - name: "Gather instance info"
      ec2_instance_info:
        filters:
          "tag:Name": "{{ ec2_name }}"
          instance-state-name: running
      register: _instances_info
    
    - assert:
        that:
          - _instances_info.instances | length == 1
          - _instances_info.instances.0.network_interfaces | length == 1

```

### Expected Results

module should not attach interface to the instance

### Actual Results

```console (paste below)

```
module attach the network interface to the instance

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
