### ISSUE TITLE
Support image_uri

### ISSUE THREAD

**Issue by manuelschneider** [ansible-collections/amazon.aws#1417]
### Summary

Please support lambdas from custom containers in AWS ECR.

There have been a pull request here: https://github.com/ansible-collections/community.aws/pull/772

I have created a patch, but no tests yet - thus no pull request. But in case somebody else has time to finish it, I wanted to share my work.

https://github.com/ansible-collections/amazon.aws/compare/main...manuelschneider:amazon.aws:main

Thank you very much for the modules!

### Issue Type

Feature Idea

### Component Name

lambda

### Additional Information

```yaml (paste below)
-   name: "Create and/or configure the lambda {{ lambda.key }}"
    amazon.aws.lambda:
        profile: "{{ awsProfile }}"
        region: "{{ aws_region }}"
        state: present
        name: "{{ lambda.key }}"
        role: arn:aws:iam::123456:role/myrole"
        image_uri: 123456.dkr.ecr.eu-central-1.amazonaws.com/mycontainer:stage
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
