### ISSUE TITLE
Provide support for AWS S3 Public Access Blocking

### ISSUE THREAD

**Issue by sky-amoncadot** [ansible-collections/amazon.aws#144]
##### SUMMARY

Support public access blocking on S3 buckets.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

[aws_s3.py](https://github.com/ansible-collections/amazon.aws/blob/main/plugins/modules/aws_s3.py) and/or [s3_bucket.py](https://github.com/ansible-collections/amazon.aws/blob/main/plugins/modules/s3_bucket.py)

##### ADDITIONAL INFORMATION

Original feature request [here](https://github.com/ansible/ansible/issues/62302).

[AWS release info](https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html).

Public access blocking is a new AWS S3 capability that ensures a bucket is much more private than even the default and that the bucket cannot subsequently be configured to have some public capabilities.

This is detached from S3 bucket policies or permissions as it is a separate API entirely. Its part of S3Control in botocore if I recall. An example of what is being requested as a native feature in Ansible:

```yaml
aws s3api put-public-access-block --bucket "${BUCKET_NAME}" --public-access-block-configuration '{
  "BlockPublicAcls": true,
  "IgnorePublicAcls": true,
  "BlockPublicPolicy": true,
  "RestrictPublicBuckets": true
}'
```

(Above snippet taken from [here]( https://github.com/tmknom/terraform-bucket-initializer/blob/a68a0c0d1f20dc3b3bd5baeaf3b8372953de6e70/init#L49-L54
).)

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/s3_bucket.py`](https://github.com/ansible-collections/amazon.aws/blob/main/plugins/modules/s3_bucket.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @jillr @s-hertel @tremble @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by zeten30** [comment]
@sky-amoncadot I've hit the same problem with blocking public access. I'll try to prepare a merge request soon.

**Comment by zeten30** [comment]
So I have a working prototype:)

```yaml
- hosts: localhost
  gather_facts: false

  tasks:
    - amazon.aws.s3_bucket:
        name: "<bucket_name>"
        state: present
        public_access:
          BlockPublicAcls: true
          # IgnorePublicAcls: false
          # BlockPublicPolicy: false
          # RestrictPublicBuckets: false
      register: module_result

    - debug:
        var: module_result

```

```yaml
ansible-playbook -i ../inventory/ s3-bucket-testing.yml  

PLAY [localhost] **************************************************************************************************************************

TASK [amazon.aws.s3_bucket] ***************************************************************************************************************
changed: [localhost]

TASK [debug] ******************************************************************************************************************************
ok: [localhost] => 
  module_result:
    changed: true
    failed: false
    name: <bucket_name>
    policy: null
    public_access_block:
      BlockPublicAcls: true
      BlockPublicPolicy: false
      IgnorePublicAcls: false
      RestrictPublicBuckets: false
    requester_pays: false
    tags: {}
    versioning:
      MfaDelete: Disabled
      Versioning: Disabled

PLAY RECAP ********************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

```shell
aws s3api get-public-access-block --bucket <bucket_name>
{
    "PublicAccessBlockConfiguration": {
        "BlockPublicAcls": true,
        "IgnorePublicAcls": false,
        "BlockPublicPolicy": false,
        "RestrictPublicBuckets": false
    }
}

```
I'll do few more tests & prepare merge request.
