### ISSUE TITLE
Add support for CALCULATED type in route53_health_check

### ISSUE THREAD

**Issue by JeffreyRodriguez** [ansible-collections/amazon.aws#1442]
### Summary

We've had the need to create CALCULATED health checks for Route53, which is not currently supported by the `route53_health_check` module.

I've done some initial work to support creating and updating CALCULATED health checks, [see this gist](https://gist.github.com/JeffreyRodriguez/dc1c4bcdacab456c0217001807b481f8) for an updated module.

Module file in repo: https://github.com/ansible-collections/amazon.aws/blob/main/plugins/modules/route53_health_check.py

### Issue Type

Feature Idea

### Component Name

route53_health_check

### Additional Information

```yaml (paste below)

- name: Create Calculated Health Check
    route53_health_check:
        health_check_name: "my_calculated_health_check"
        use_unique_names: true
        type: CALCULATED
        failure_threshold: 3
        child_health_checks: "{{ child_health_check_ids }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
