### ISSUE TITLE
ec2_instance module reporting count or exact_count is unsupported parameters.

### ISSUE THREAD

**Issue by richardurw** [ansible-collections/amazon.aws#1447]
### Summary

When I use the ec2_instance module when using count or exact-count parameter for latest release of 5.4 I am getting

"msg": "Unsupported parameters for (amazon.aws.ec2_instance) module: count. Supported parameters include: purge_tags, tags, instance_initiated_shutdown_behavior, availability_zone, cpu_options, vpc_subnet_id (subnet_id), volumes, image_id, metadata_options, aws_access_key (access_key, ec2_access_key), network, placement_group, region (aws_region, ec2_region), tower_callback, filters, detailed_monitoring, tenancy, validate_certs, security_token (access_token, aws_security_token), wait, name, profile (aws_profile), ebs_optimized, security_group, aws_secret_key (ec2_secret_key, secret_key), launch_template, aws_ca_bundle, user_data, debug_botocore_endpoint_logs, instance_ids, cpu_credit_specification, security_groups, termination_protection, wait_timeout, instance_role, key_name, image, ec2_url (aws_endpoint_url, endpoint_url), state, instance_type, aws_config.",

### Issue Type

Bug Report

### Component Name

ec2_instance

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
# /root/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
amazon.aws      5.4.0  
ansible.windows 1.10.0 
community.aws   5.4.0  

# /usr/share/ansible/collections/ansible_collections
Collection      Version
--------------- -------
amazon.aws      5.4.0  
ansible.windows 1.10.0 
community.aws   5.4.0  
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
Name: boto3
Version: 1.26.99
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: s3transfer, jmespath, botocore
Required-by: 
---
Name: botocore
Version: 1.29.99
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: python-dateutil, urllib3, jmespath
Required-by: s3transfer, boto3
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/sh
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/root/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
```

### Steps to Reproduce

```yaml (paste below)
- name: EC2 provisoning 
    amazon.aws.ec2_instance:
      name: "{{ i_name }}"
      key_name: witbizkey
      security_group: "{{ security_group }}"
      instance_type: "{{ i_type }}"
      instance_role: "{{ i_iam_role }}"
      image_id: "{{ win_ami.image_id }}"
      termination_protection: "{{ i_term_protection }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp3
          volume_size: "{{ i_vol }}"
          delete_on_termination: "{{ i_vol_term }}"
        - device_name: xvdf
          volume_type: gp3
          volume_size: "{{ i_vol2 }}"
          delete_on_termination: "{{ i_vol_term }}" 
      vpc_subnet_id: "{{ subnet_ids }}"
      user_data: "{{ lookup('template', 'userdata.winrmtmp.j2') }}"    
#      count_tag:
#          Name: "{{ i_name }}"
      count: "{{ i_count }}"
```

### Expected Results

I expect the ec2 instance to be created in my AWS account with the count number that is selected. 

### Actual Results

```console (paste below)
{
  "msg": "Unsupported parameters for (amazon.aws.ec2_instance) module: count. Supported parameters include: purge_tags, tags, instance_initiated_shutdown_behavior, availability_zone, cpu_options, vpc_subnet_id (subnet_id), volumes, image_id, metadata_options, aws_access_key (access_key, ec2_access_key), network, placement_group, region (aws_region, ec2_region), tower_callback, filters, detailed_monitoring, tenancy, validate_certs, security_token (access_token, aws_security_token), wait, name, profile (aws_profile), ebs_optimized, security_group, aws_secret_key (ec2_secret_key, secret_key), launch_template, aws_ca_bundle, user_data, debug_botocore_endpoint_logs, instance_ids, cpu_credit_specification, security_groups, termination_protection, wait_timeout, instance_role, key_name, image, ec2_url (aws_endpoint_url, endpoint_url), state, instance_type, aws_config.",
  "invocation": {
    "module_args": {
      "name": "USDTC1TWTEST001",
      "key_name": "witbizkey",
      "security_group": "['allow-ms-ad-traffic']",
      "instance_type": "t3.small",
      "instance_role": "EC2_Metadata_Tagging",
      "image_id": "ami-0b8508d946afbf024",
      "termination_protection": false,
      "volumes": [
        {
          "device_name": "/dev/sda1",
          "volume_type": "gp3",
          "volume_size": 100,
          "delete_on_termination": "true"
        },
        {
          "device_name": "xvdf",
          "volume_type": "gp3",
          "volume_size": 0,
          "delete_on_termination": "true"
        }
      ],
      "vpc_subnet_id": "subnet-0a7256f4a49cccf51",
      "user_data": "<powershell>\n### Set Timezone to PDT\ntzutil /s \"Pacific Standard Time\"\n\n### Initialize raw disk volume within OS\n$diskNumber = (Get-Disk | ? {($_.OperationalStatus -eq \"Online\") -and ($_.\"PartitionStyle\" -eq \"RAW\") }).Number\nInitialize-Disk -Number $diskNumber -PassThru\n\n$part = New-Partition -DiskNumber $diskNumber -UseMaximumSize -AssignDriveLetter\nFormat-Volume -DriveLetter $part.DriveLetter -Confirm:$FALSE\n\n### Disable all firewall profile\nSet-NetFirewallProfile -Profile Domain, Public, Private -Enabled False\n\n### Setup winrm for http access\nwinrm set winrm/config/service '@{AllowUnencrypted=\"true\"}'\nwinrm set winrm/config/service/auth '@{Basic=\"true\"}'\n\n### Rename EC2 instance Windows OS to match tag\n$instanceId = (invoke-webrequest http://169.254.169.254/latest/meta-data/instance-id -UseBasicParsing).content\n$nameValue = (get-ec2tag -filter @{Name=\"resource-id\";Value=$instanceid},@{Name=\"key\";Value=\"Name\"}).Value\n#$nameValue = (invoke-webrequest http://169.254.169.254/latest/meta-data/tags/instance/Name -UseBasicParsing).content\n$pattern = \"^(?![0-9]{1,15}$)[a-zA-Z0-9-]{1,15}$\"\n#Verify Name Value satisfies best practices for Windows hostnames\nIf ($nameValue -match $pattern) \n    {Try\n        {Rename-Computer -NewName $nameValue -Restart -ErrorAction Stop} \n    Catch\n        {$ErrorMessage = $_.Exception.Message\n        Write-Output \"Rename failed: $ErrorMessage\"}}\nElse\n    {Throw \"Provided name not a valid hostname. Please ensure Name value is between 1 and 15 characters in length and contains only alphanumeric or hyphen characters\"}\n\n</powershell>",
      "count": 1,
      "debug_botocore_endpoint_logs": false,
      "validate_certs": true,
      "state": "present",
      "wait": true,
      "wait_timeout": 600,
      "security_groups": [],
      "purge_tags": false,
      "instance_ids": [],
      "ec2_url": null,
      "aws_access_key": null,
      "aws_secret_key": null,
      "security_token": null,
      "aws_ca_bundle": null,
      "profile": null,
      "aws_config": null,
      "region": null,
      "image": null,
      "tower_callback": null,
      "ebs_optimized": null,
      "availability_zone": null,
      "tags": null,
      "filters": null,
      "launch_template": null,
      "cpu_credit_specification": null,
      "cpu_options": null,
      "tenancy": null,
      "placement_group": null,
      "instance_initiated_shutdown_behavior": null,
      "detailed_monitoring": null,
      "network": null,
      "metadata_options": null
    }
  },
  "_ansible_no_log": false,
  "changed": false
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mandar242** [comment]
Hi @richardurw, thank you for reporting this.
I tried reproducing the error but was not able to, need to dig more into it. also, please note the usage of volume parameters below.

tried a simple task, worked as expected to create the instances
```
    - name: EC2 provisoning
      amazon.aws.ec2_instance:
        name: "{{ i_name }}"
        instance_type: "{{ i_type }}"
        image_id: "{{ image_id }}"
        count: "{{ i_count }}"
        vpc_subnet_id: "{{ subnet_id }}"
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_type: gp3
              volume_size: "{{ i_vol }}"
              delete_on_termination: "{{ i_vol_term }}"
          - device_name: xvdf
            ebs:
              volume_type: gp3
              volume_size: "{{ i_vol2 }}"
              delete_on_termination: "{{ i_vol_term }}"
```

collection version
```
# /Users/mk/venv3.9/lib/python3.9/site-packages/ansible_collections
Collection Version
---------- -------
amazon.aws 5.4.0 
```

**Comment by richardurw** [comment]
Hi @mandar242 so you tested instance creation with the count and it works properly?

**Comment by mandar242** [comment]
> Hi @mandar242 so you tested instance creation with the count and it works properly?

@richardurw yes worked fine for me creating multiple instances, not entirely sure what could be going wrong on your end, I can investigate more to see if I can find the issue

**Comment by richardurw** [comment]
@mandar242 its kind of strange that the parameters it output in the error doesn't have count or exact_count as an option but in the ansible collection for 5.4 documentation it has it.

**Comment by tremble** [comment]
@richardurw The error message you've posted looks distinctly like you've got an old version of amazon.aws installed somewhere.  Ansible supports multiple copies of collections being installed and does **not** simply prefer the latest.  Specifically it looks like you've got amazon.aws 2.0.0 or 2.1.0 installed.

Could you provide the full output of `ansible-galaxy list` please.

**Comment by richardurw** [comment]
@tremble below is what I have when ansible-galaxy collection list is perform. 

[root@USDTC1PAAP001 ec2-user]# ansible-galaxy collection list

# /root/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
amazon.aws      5.4.0  
ansible.windows 1.10.0 
community.aws   5.4.0  

# /usr/share/ansible/collections/ansible_collections
Collection      Version
--------------- -------
amazon.aws      5.4.0  
ansible.windows 1.10.0 
community.aws   5.4.0

**Comment by tremble** [comment]
Could you try uninstalling and re-installing the amazon.aws and community.aws collections, something's a little weird there.

**Comment by richardurw** [comment]
@tremble do you know if this version is backward compatible with the previous versions that was using ec2.py module? I have some playbooks that was using that module before. And until I am sure this new collection works I really don't want to break the playbook runs.

**Comment by tremble** [comment]
@richardurw 
The `ec2` module was dropped in release 4.0.0 and `ec2_instance` isn't an direct drop-in replacement.  Parameter names and the format of what the parameters takes is subtly different across the two modules - for example count_tags was replaced by the "filters" parameter which lets you perform the matching based on more than just tags.  This was done very deliberately and is why the two modules were available in parallel for so long.

**Comment by ansibullbot** [comment]
cc @jillr @ryansb @s-hertel
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by richardurw** [comment]
> Hi @richardurw, thank you for reporting this. I tried reproducing the error but was not able to, need to dig more into it. also, please note the usage of volume parameters below.
> 
> tried a simple task, worked as expected to create the instances
> 
> ```
>     - name: EC2 provisoning
>       amazon.aws.ec2_instance:
>         name: "{{ i_name }}"
>         instance_type: "{{ i_type }}"
>         image_id: "{{ image_id }}"
>         count: "{{ i_count }}"
>         vpc_subnet_id: "{{ subnet_id }}"
>         volumes:
>           - device_name: /dev/sda1
>             ebs:
>               volume_type: gp3
>               volume_size: "{{ i_vol }}"
>               delete_on_termination: "{{ i_vol_term }}"
>           - device_name: xvdf
>             ebs:
>               volume_type: gp3
>               volume_size: "{{ i_vol2 }}"
>               delete_on_termination: "{{ i_vol_term }}"
> ```
> 
> collection version
> 
> ```
> # /Users/mk/venv3.9/lib/python3.9/site-packages/ansible_collections
> Collection Version
> ---------- -------
> amazon.aws 5.4.0 
> ```

@mandar242 do you see an issue with the way the volume parameters is written in the playbook? I reference the documentation in the amazon.aws 5.4.0. Let me know if it should be written out a different way.

**Comment by mandar242** [comment]
@richardurw the example you have specified in the issue description does not use `ebs` 
so imo, this
```
      volumes:
        - device_name: /dev/sda1
          volume_type: gp3
          volume_size: "{{ i_vol }}"
          delete_on_termination: "{{ i_vol_term }}"
```
should be 
```
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_type: gp3
              volume_size: "{{ i_vol }}"
              delete_on_termination: "{{ i_vol_term }}"
```
