### ISSUE TITLE
EC2 module errors out since it incorrectly includes terminated instances

### ISSUE THREAD

**Issue by trondhindenes** [ansible-collections/amazon.aws#146]
##### SUMMARY
Given this task:
```yaml
    - name: stop ec2 instances
      ec2:
        region: eu-west-1
        state: stopped
        wait: yes
        instance_tags:
          strange-dog-match-tag: "what"
```
If there are existing (recently) terminated ec2 instances matching that tag, Ansible will error out with this message:
`"Unable to change state for instance i-03bb1408d136a9a4b, error: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>IncorrectInstanceState</Code><Message>This instance 'i-03bb1408d136a9a4b' is not in a state from which it can be stopped.</Message></Error></Errors><RequestID>d35eac01-6fa2-4c62-9763-3a5a08651a5c</RequestID></Response>"}`

This seems to happen because Ansible considers all instances matching the `instance_tags`, including terminated instances. The correct behaviour would be to only consider non-terminated instances for all evaluations

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION
```paste below
ansible 2.9.12
  config file = None
  configured module search path = ['/home/trond/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

```

##### CONFIGURATION
```paste below
N/A
```

##### OS / ENVIRONMENT
Ubuntu 20.04

##### STEPS TO REPRODUCE
See description above

##### EXPECTED RESULTS
Ansible should disregard terminated instances and not error out

##### ACTUAL RESULTS
See description
