### ISSUE TITLE
aws_ec2 inventory example doesn't match documented type for hostnames

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible-collections/amazon.aws#1460]
### Summary

For [aws_ec2 inventory](https://ansible-collections.github.io/amazon.aws/branch/main/collections/amazon/aws/aws_ec2_inventory.html#ansible-collections-amazon-aws-aws-ec2-inventory), the documentation for `hostnames` says "list / elements=dictionary" with key `name` being required.

But in the example there's a list of `union[dictionary|str]`:

```
hostnames:
  - tag:Name=Tag1,Name=Tag2  # Return specific hosts only
  - tag:CustomDNSName
  - dns-name
  - name: 'tag:Name=Tag1,Name=Tag2'
  - name: 'private-ip-address'
    separator: '_'
    prefix: 'tag:Name'
  - name: 'test_literal' # Using literal values for hostname
    separator: '-'       # Hostname will be aws-test_literal
    prefix: 'aws'
```

At a glance, it looks like the example should not work, because it doesn't match the `hostnames` docs.
In particular, since these strings contain colons, will Ansible interpret this as `{"tag": "CustomDNSName"}`?

If the module allows type types of list members, one string, one dict, the documentation should say so.

### Issue Type

Documentation Report

### Component Name

aws_ec2 inventory

### Ansible Version

N/A

### Collection Versions

N/A

### Configuration

N/A

### OS / Environment

N/A

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
