### ISSUE TITLE
ec2_instance module return values contains information about instances created in previous runs.

### ISSUE THREAD

**Issue by UNiXMIT** [ansible-collections/amazon.aws#1471]
### Summary

I create 1 instance using the ec2_instance module. I register the return values using 'register: ec2'. I then use the 'add_host' module with "loop: '{{ ec2.instances }}'" to add the IP addresses of the instance just created. I use this IP address to dynamically create the hosts in memory using add_host.
If I run the play again without changing any variables, ec2-instances will now return 2 instances when I only want the return information from the 1 instance I created in that run of the playbook.
How can I only get ec2_instance to return the information only for the instance created in that current run of the play and not all instances in my AWS account that have the same name.
Is there something different I should be doing to only get information returned about instances created in the current run only?

### Issue Type

Bug Report

### Component Name

ec2_instance

### Ansible Version

```
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.14 (main, Jan  9 2023, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

### Collection Versions

```
amazon.aws 5.4.0
```

### AWS SDK versions

```
Name: boto3
Version: 1.26.87
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: s3transfer, jmespath, botocore
Required-by: pfsso
---
Name: botocore
Version: 1.29.87
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: urllib3, jmespath, python-dateutil
Required-by: s3transfer, boto3
```

### Configuration

N/A

### OS / Environment

Rocky Linux 9.1

### Steps to Reproduce

```
- name: AWS EC2 Management
  hosts: local
  gather_facts: no
  tasks:
  - name: Create AWS EC2 instance
    ec2_instance:
      aap_callback:
        windows: true
        set_password: '{{ myPassword }}'
      name: '{{ semaphore_vars.task_details.username|upper }}-{{ imageName }}'
      image_id: '{{ awsAMI }}'
      key_name: '{{ keyName }}'
      network:  
        assign_public_ip: yes
      security_group: '{{ securityGroup }}'
      region: '{{ awsRegion }}'
      availability_zone: '{{ availabilityZone }}'
      aws_profile: '{{ awsProfile }}'
      instance_type: '{{ instanceType }}'
      count: '{{ vmCount }}'
      volumes:
      - device_name: '{{ deviceName }}'
        ebs:
         volume_type: '{{ volumeType }}'
         volume_size: '{{ volumeSize }}'
      state: running
      wait: true
    register: ec2

- name: Add Host to awsEC2 Group 
    add_host: 
       hostname: '{{ item.public_ip_address }}'
       ansible_user: '{{ ansibleUser }}'
       ansible_password: '{{ myPassword }}'
       ansible_connection: winrm
       ansible_winrm_transport: basic
       ansible_winrm_server_cert_validation: ignore
       ansible_port: 5986
       groups: awsEC2
    loop: '{{ ec2.instances }}'
```

### Expected Results

I would expect the return values to only contain instances created in that current run.

### Actual Results

Run this 2 times. The second time you run it the return values will contain the information about the instance created in the current run and also the information about the instance created in the previous run.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
