### ISSUE TITLE
Add support to inventory MQ brokers

### ISSUE THREAD

**Issue by alialkhalidi** [ansible-collections/amazon.aws#1571]
### Summary

MQ brokers' Ansible life-cycle support is coming with version 6.0.0 of the collection. The tooling can be greatly streamlined with the ability to inventory the brokers in a similar fashion as ec2 and rds resources. The inventory is useful even with workflows involving native MQ (ActiveMQ or RabbitMQ) tooling, as a precursor to manage the configuration for these type resources. 

### Issue Type

Feature Idea

### Component Name

aws_mq

### Additional Information

```yaml
plugin: aws_mq
regions:
  - ca-central-1
keyed_groups:
  - key: engine_type
    prefix: mq
compose:
  app: 'tags.Applications|split(",")'
hostvars_prefix: aws_
hostvars_suffix: _mq
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
