### ISSUE TITLE
ec2_instance / key_name assume not provided if empty

### ISSUE THREAD

**Issue by nesies** [ansible-collections/amazon.aws#1594]
### Summary

When using ec2_instance to create Linux or Windows instances, Windows do not requires key_name but Linux do.

To use same ec2_instance call for both OS, key_name empty might be considered "not set" instead of raising an error

### Issue Type

Feature Idea

### Component Name

ec2_instance

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by gravesm** [comment]
@nesies Could you clarify what the problem is you are trying to solve here? An empty value in YAML gets translated to `None` in Python, so the module already supports what you want to do.

This task:
```
- amazon.aws.ec2_instance:
    name: my-instance
    vpc_subnet_id: some-id
    instance_type: t3.micro
    security_group: default
    network:
      assign_public_ip: true
    image_id: ami-123456
```
is equivalent to this task:
```
- amazon.aws.ec2_instance:
    name: my-instance
    key_name:
    vpc_subnet_id: some-id
    instance_type: t3.micro
    security_group: default
    network:
      assign_public_ip: true
    image_id: ami-123456
```

**Comment by nesies** [comment]
The actual code do not pass key_name to AWS if key_name is None.
But it pass key_name when it is an empty string "", and the AWS API do not like it.

My change makes amazon.aws.ec2_instance handle "" the same way of None -> do not pass it to AWS API


**Exemple when key_name == "":**

When providing an empty key_name, i get an error with this message:

 "msg": "Failed to create new EC2 instance: An error occurred (InvalidParameterValue) when calling the RunInstances operation: Invalid value '' for keyPairNames. It should not be blank",


```
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create EC2
      amazon.aws.ec2_instance:
        region: "{{ lookup('ansible.builtin.env', 'AWS_REGION') }}"
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        image_id: "{{ var_image_id }}"
        instance_type: t3.nano
        name: test001
        vpc_subnet_id: "{{ var_subnet_id }}"
        key_name: "{{ var_key_name | default('') }}"
```
