### ISSUE TITLE
rds_cluster: Add support for more states (stopped, started, restarted)

### ISSUE THREAD

**Issue by ohmer** [ansible-collections/amazon.aws#1616]
### Summary

I am trying to implement a playbook to stop and start an application environment to save money.
The stack includes RDS Aurora clusters and the AWS collection only support present and absent states.

AWS added support to interrupt RDS cluster temporarily with some caveat:
- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_StopInstance.html
- https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-cluster-stop-start.html

It would be great to have support for these additional states for us and the community. Automated solution exists (example: https://aws.amazon.com/blogs/database/save-costs-by-automating-the-start-and-stop-of-amazon-rds-instances-with-aws-lambda-and-amazon-eventbridge/) but I would like to provide the flexibility to our development team to do it on demand, not on schedule.

### Issue Type

Feature Idea

### Component Name

rds_cluster

### Additional Information

```yaml (paste below)
- name: Get database cluster information
  amazon.aws.rds_cluster_info:
    cluster_name: "{{ rds_cluster_name }}"
    region: "{{ aws_region }}"
  register: cluster_info

- name: Stop database cluster (AWS restarts it automatically after 7 days)
  amazon.aws.rds_cluster:
    db_cluster_identifier: "{{ cluster_info.clusters[0].db_cluster_identifier }}"
    state: stopped
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
