### ISSUE TITLE
EC2 module multiple subnets.

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/amazon.aws#164]
_From @andrew-pickin-epi on Sep 18, 2020 22:05_

##### SUMMARY
EC2 module creates a number of instances. It would be useful if these were able to be spread over multiple subnets and hence AZs. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
https://docs.ansible.com/ansible/latest/modules/ec2_module.html

##### ADDITIONAL INFORMATION
Currently I might request 3 web servers, but these are all deployed to the same subnet , hence the same AZ.
If I create a subnet for each AZ, they could be distributed if the module supported multiple subnets.

```yaml
- ec2:
    key_name: mykey
    group: webservers
    instance_type: t2.micro
    image: ami-123456
    wait: yes
    wait_timeout: 500
    count: 3
    monitoring: yes
    vpc_subnet_ids: "{{ "{{ subnet_info.subnets|map(attribute='id')|list }}"
    assign_public_ip: yes
```

_Copied from original issue: ansible/ansible#71823_
