### ISSUE TITLE
Document common authentication issues 

### ISSUE THREAD

**Issue by tremble** [ansible-collections/amazon.aws#1654]
It's less common than it used to be, however it looks like folks are still periodically having issues when they try to pull credentials from the credentials file.  We now mention the Host vs Controller gotcha in the Notes section of all modules, but we should probably also mention the "become" gotcha (see below).  I think it's worth tweaking the Note a little further, but I'm also thinking it might be worth tweaking the the README and the AWS Guide...

Found out why! This cost me hours, and right after I've posted this bug I realized I was  running it with `sudo` locally, and root doesn't have the AWS credential file. I've added the `become: false` and it is working now:

```yaml
---
- name: Ensure A record
  community.aws.route53:
    state: present
    zone: mydomain.net
    record: lisa.mydomain.net
    type: A
    ttl: 60
    value: 127.0.0.1
    wait: no
  delegate_to: localhost
  become: false
```

Silly me.

_Originally posted by @danielmanser in https://github.com/ansible-collections/community.aws/issues/708#issuecomment-917458977_
