### ISSUE TITLE
Where is ec2_asg?

### ISSUE THREAD

**Issue by onitake** [ansible-collections/amazon.aws#166]
##### SUMMARY

According to the changelog, there should be a module for modifying EC2 autoscaling groups called `ec2_asg`, but I can't find it anywhere. Was this removed?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_asg

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  python version = 3.8.5 (default, Aug  2 2020, 15:09:07) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below
N/A
```

##### STEPS TO REPRODUCE

```yaml
- name: create autoscaling group
  amazon.aws.ec2_asg:
    name: test-asg
    vpc_zone_identifier: vpc_zone
    launch_config_name: lc
    desired_capacity: 1
    min_size: 1
    max_size: 1
```

##### EXPECTED RESULTS

The ASG is created.

##### ACTUAL RESULTS

```paste below
TASK [aws-infra : include_tasks] ************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"reason": "couldn't resolve module/action 'amazon.aws.ec2_asg'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in 'xxx.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: create autoscaling group\n  ^ here\n"}
```
