### ISSUE TITLE
ec2_vpc_igw should be able to remove detached internet gateway

### ISSUE THREAD

**Issue by branic** [ansible-collections/amazon.aws#1669]
### Summary

I am trying to delete an internet gateway that is in a detached state.

The way the ec2_vpc_igw module currently works a `vpc_id` has to be supplied and the igw is deleted based on looking up the igw by the vpc_id, then it is detached from the VPC and finally deleted. This makes it such that igws in a detached state cannot be deleted.

It would be useful to be able to supply an `internet_gateway_id` and have the module detach it from the VPC if needed and then delete it.

### Issue Type

Feature Idea

### Component Name

ec2_vpc_igw

### Additional Information

```yaml (paste below)
---
- name: Testing playbook
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Gather internet gateway info
      amazon.aws.ec2_vpc_route_table_info:
        profile: <<REDACTED>>
        region: us-east-2
      register: aws_igws

    - name: Remove internet gateways
      amazon.aws.ec2_vpc_igw:
        profile: <<REDACTED>>
        region: us-east-2
        internet_gateway_id: "{{ igw['internet_gateway_id'] }}"
        state: absent
      loop: "{{ aws_igws['internet_gateways'] }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
