### ISSUE TITLE
aws_s3 encryption_mode "aws:kms" is not working

### ISSUE THREAD

**Issue by sagar89jadhav** [ansible-collections/amazon.aws#168]
##### SUMMARY
Hi,

I am trying to apply default encrytion as "aws:kms" to s3 bucket which was created earlier however, I am getting below error;

```
fatal: [localhost]: FAILED! => {
    "msg": "Could not find imported module support code for aws_s3.  Looked for either HAS_MD5.py or s3.py"
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`aws_s3` module

##### ANSIBLE VERSION

```
2.6.2
```

##### CONFIGURATION

```
  - name: Create S3 bucket
    aws_s3:
      bucket: "{{aws_environment}}-mybucket"
      mode: create
      encrypt: yes
      encryption_kms_key_id: "arn:aws:kms:{{aws_environment}}:{{project_name}}:key/{{kmskey}}"
      encryption_mode: aws:kms
      region: "{{aws_region}}"

```

##### OS / ENVIRONMENT
CircleCI docker container linux based.

##### STEPS TO REPRODUCE
Use ansible version lower than 2.7. Currently 2.6.2 is getting used in my project.

##### EXPECTED RESULTS
AWS s3 bucket default encryption should get enabled with an encryption as aws:kms.

##### ACTUAL RESULTS
Bucket is getting created but default encryption is remained as "None" in aws console. In short, changes are not getting reflected.
```Note:- Based on suggestion provided in "https://github.com/ansible/ansible/issues/72002" I have followed multiple "aws_s3.py" libraries mentioned in tags `1.0.0, 1.1.0` but didnt get a success. Can you help where should I find supported aws_s3.py library which can help to solve s3 encryption problem?```
