### ISSUE TITLE
PrivateDnsEnabled in create_vpc_endpoint - ec2_vpc_endpoint

### ISSUE THREAD

**Issue by krisek** [ansible-collections/amazon.aws#1719]
### Summary

I don't find an option to enable private dns in the ec2_vpc_endpoint module. Interestingly boto3 documentation says that the `PrivateDnsEnabled` parameter in the `create_vpc_endpoint` call is by default `True`. 

I don't see any sing of this in `ec2_vpc_endpoint.py`, can be that it would be a 2 liner in  ec2_vpc_endpoint.create_vpc_endpoint (+docs update) to add this parameter?

### Issue Type

Bug Report

### Component Name

ec2_vpc_endpoint

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.14.4]
  config file = /home/kris/projects/k8s-ansible/cluster-manage/ansible.cfg
  configured module search path = ['/home/kris/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/tmp/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/kris/.ansible/collections:/usr/share/ansible/collections
  executable location = /var/tmp/ansible/bin/ansible
  python version = 3.11.4 (main, Jun  7 2023, 10:13:09) [GCC 12.2.0] (/var/tmp/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = False

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
amazon.aws                    7.0.0-dev0                                                                                                                                                                                  
...
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /var/tmp/ansible/lib/python3.11/site-packages
Requires: 
Required-by: 
---
Name: boto3
Version: 1.26.100
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /var/tmp/ansible/lib/python3.11/site-packages
Requires: botocore, jmespath, s3transfer
Required-by: 
---
Name: botocore
Version: 1.29.100
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /var/tmp/ansible/lib/python3.11/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: awscli, boto3, s3transfer

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
  - name: apply vpc endpoint
    amazon.aws.ec2_vpc_endpoint:
      state: present
      region: "{{ region }}"
      vpc_id: "{{ vpc_info.vpcs.0.vpc_id }}"
      service: "{{ item.name }}"
      vpc_endpoint_security_groups: "{{ security_group_info.security_groups | map(attribute='group_id') }}"
      vpc_endpoint_subnets: "{{ peerable_subnets| selectattr('availability_zone', subnet_filter, item.az)  | map(attribute='subnet_id') }}"
      vpc_endpoint_type: Interface
      purge_tags: n
      tags: "{{ default_tags | combine({'Name': service.name | default('service-' ~ item.name) ~ '-' ~ inventory_hostname ~ '-' ~ item.az}) }}"
      profile: "profile_{{ aws_account }}"
    register: vpc_endpoint_result
    loop: "{{ service.endpoint_services }}"
    loop_control:
      label: "{{ item.name }}"
    tags: [ implement ]

```

### Expected Results

PrivateDns is enabled (or not?) for the created endpoint

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
