### ISSUE TITLE
aws_secret Returning the value instead of key/pair

### ISSUE THREAD

**Issue by mariesheilag** [ansible-collections/amazon.aws#173]
##### SUMMARY

Trying to get valuer of our API Keys in the AWS Secret Manager. Do you know how to parse and only get the value instead of returning key/pair?

##### ANSIBLE VERSION

```paste below
2.9.10
```

##### CONFIGURATION

```paste below
ansible-galaxy collection install amazon.aws
```

##### STEPS TO REPRODUCE

```yaml
Run your ansible-playbook

vars:
api_key: "{{ lookup('aws_secret', 'api_key', region='ap-southeast-1') }}"
```

##### EXPECTED RESULTS

Only the API Key Value.

##### ACTUAL RESULTS

```paste below
"{'api_key': '<api_key_value>'}"
```
