### ISSUE TITLE
elb_application_lb_info - Ability to filter results

### ISSUE THREAD

**Issue by andreiboost** [ansible-collections/amazon.aws#1767]
### Summary

`elb_application_lb_info` doesn't have any option to filter/query specific ELBs beyond lookup by ARN/name. I am trying to filter by VPC ID, but this is not possible with this module. For example `amazon.aws.ec2_security_group_info` supports this exact case, i.e.

```yml
- name: Find all Security Groups
  amazon.aws.ec2_security_group_info:
    filters:
      vpc-id: "vpc-12345"
```

To achieve the same result with ALBs, I have to resort to the AWS CLI, for example:

```yml
- name: Get VPC ALBs
  check_mode: false
  changed_when: false
  ansible.builtin.command:
    cmd: >-
      aws elbv2 describe-load-balancers
      --query 'LoadBalancers[?VpcId==`vpc-12345` && Type==`application`]'
      --output json
  register: __cluster_albs_json

- name: Parse ALB output
  ansible.builtin.set_fact:
    cluster_albs: "{{ __cluster_albs_json.stdout | from_json }}"
```

For my purposes, this works but the output isn't the same nor as complete as `elb_application_lb_info`. Please consider adding a `filters` parameter to this module. `elb_application_lb_info` often fails due to throttling in accounts with many ALBs, i.e.
> Failed to describe listener rules: An error occurred (Throttling) when calling the DescribeRules operation (reached max retries: 4): Rate exceeded

### Issue Type

Feature Idea

### Component Name

elb_application_lb_info

### Additional Information

```yaml
- name: Find all ALBs in VPC
  amazon.aws.elb_application_lb_info:
    filters:
      vpc-id: "vpc-12345"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
