### ISSUE TITLE
Support For Additional Placement Options and LicenseSpecifications

### ISSUE THREAD

**Issue by mfortin** [ansible-collections/amazon.aws#1824]
### Summary

In order to launch mac instances using the `amazon.aws.ec2_instance` module, support for HostGroupResourceArn placement option and LicensConfigurations would be required as an alternative to only specifying tenancy as dedicated to offer more control on instance launch.

### Issue Type

Feature Idea

### Component Name

ec2_instance

### Additional Information

```yaml
- name: start a mac instance with a host resource group and license configuration
  amazon.aws.ec2_instance:
    name: "public-compute-instance"
    key_name: "prod-ssh-key"
    vpc_subnet_id: subnet-5ca1ab1e
    instance_type: mac1.metal
    security_group: default
    placement:
      hostresourcegrouparn: arn:aws:resource-groups:us-east-1:123456789012:group/MyResourceGroup
    license_specifications:
      - licence_configuration_arn: 
    image_id: ami-123456
    tags:
      Environment: Testing
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
