### ISSUE TITLE
EC2 Inventory Plugin parameter use_ssm_inventory is not effective

### ISSUE THREAD

**Issue by vijayreddiar** [ansible-collections/amazon.aws#1977]
### Summary

EC2 Inventory Plugin parameter `use_ssm_inventory` is not effective irrespective of the count of instances in the account.

### Issue Type

Bug Report

### Component Name

aws_ec2

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.9]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.18 (main, Jan 24 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list

# /usr/share/ansible/collections/ansible_collections
Collection              Version
----------------------- -------
amazon.aws              7.3.0
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
WARNING: Package(s) not found: boto
Name: boto3
Version: 1.34.42
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: botocore, jmespath, s3transfer
Required-by:
---
Name: botocore
Version: 1.34.42
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: boto3, s3transfer
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
hostnames:
  - name: tag:Name
    prefix: ""
compose:
  ansible_host: private_ip_address
groups:
  linux: "'windows' not in platform_details|lower"
  windows: "'windows' in platform_details|lower"
use_ssm_inventory: true
```

### Expected Results

Above inventory source code in AWX fetch `ssm_inventory` host variable as below.

```console (paste below)
ssm_inventory:
  agent_type: amazon-ssm-agent
  agent_version: 3.2.2222.0
  computer_name: wmgtpadoagt01.WORKGROUP
  instance_id: i-032a8eda18421b1e4
  instance_status: Active
  ip_address: 10.255.26.83
  platform_name: Microsoft Windows Server 2022 Datacenter
  platform_type: Windows
  platform_version: 10.0.20348
  resource_type: EC2Instance
```

### Actual Results

No `ssm_inventory` host variable
```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
