### ISSUE TITLE
`amazon.aws.s3_bucket` module cannot configure object-lock-configuration

### ISSUE THREAD

**Issue by hydezhao** [ansible-collections/amazon.aws#2034]
### Summary

When using the cli , we can do `aws s3api put-object-lock-configuration` to configure the object-lock configuration. While it cannot be done via the ansible module `amazon.aws.s3_bucket`.

### Issue Type

Bug Report

### Component Name

s3_bucket

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.8]
  python version = 3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.3.9.4)] 
  jinja version = 3.1.2
  libyaml = True
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list

amazon.aws            7.4.0
```

### AWS SDK versions

```console (paste below)

$ pip show boto boto3 botocore

Name: boto3
Version: 1.34.75

Name: botocore
Version: 1.34.75
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

object-lock-configuration can be set via this module

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mandar242** [comment]
Hi @hydezhao , thank you for reporting. I believe that expected functionality exists in the amazon.aws.s3_bucket module.
for more information https://docs.ansible.com/ansible/latest/collections/amazon/aws/s3_bucket_module.html#examples
With use of parameters `object_lock_enabled` and `object_lock_default_retention`, the object lock configuration can be set.
```
    - amazon.aws.s3_bucket:
        name: my-test-bucket
        state: present
        object_lock_enabled: true
        object_lock_default_retention:
          mode: GOVERNANCE
          days: 2
```
