### ISSUE TITLE
amazon.aws.rds_cluster module should support storage_type values for Aurora standard and IO optimized

### ISSUE THREAD

**Issue by abemusic** [ansible-collections/amazon.aws#2038]
### Summary

I am trying to manage RDS aurora clusters (in provisioned mode, not serverless) and would like to enable IO optimized storage by setting `storage_type: aurora-iopt1`, but the module only allows for the single "io1" value. Allowing additional values for this attribute would allow us to enable/disable IO optimized mode for supported Aurora clusters.

### Issue Type

Feature Idea

### Component Name

rds_cluster

### Additional Information

```yaml (paste below)
- name: Create Aurora RDS cluster
  amazon.aws.rds_cluster:
    state: present
    cluster_id: my-cluster
    engine: aurora-mysql
    engine_mode: provisioned
    engine_version: 8.0.mysql_aurora.3.04.1

    # Enable IO optimized mode when using aurora
    storage_type: aurora-iopt1

    # Enables standard mode when using aurora
    # storage_type: aurora
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
