### ISSUE TITLE
Unable to utilize AWS_CONFIG_FILE with ec2

### ISSUE THREAD

**Issue by christophert** [ansible-collections/amazon.aws#204]
Moved from ansible-collections/community.aws#306

##### SUMMARY
The environment variable `AWS_CONFIG_FILE` is not passed to/used by the ec2 module when looking up profiles/running tasks.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2.py

##### ANSIBLE VERSION
```
ansible 2.10.3
  config file = /home/ec2-user/proj/plugins/range/automation/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.virtualenvs/proj/lib/python3.7/site-packages/ansible
  executable location = /home/ec2-user/.virtualenvs/proj/bin/ansible
  python version = 3.7.9 (default, Aug 27 2020, 21:59:41) [GCC 7.3.1 20180712 (Red Hat 7.3.1-9)]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/ec2-user/proj/plugins/range/automation/ansible.cfg) = ['/home/ec2-user/proj/plugins/range/automation/inventory.aws_ec2.yml']
DEFAULT_ROLES_PATH(/home/ec2-user/proj/plugins/range/automation/ansible.cfg) = ['/home/ec2-user/proj/plugins/range/automation/roles']
DEFAULT_STDOUT_CALLBACK(/home/ec2-user/proj/plugins/range/automation/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/ec2-user/proj/plugins/range/automation/ansible.cfg) = False
PLAYBOOK_DIR(/home/ec2-user/proj/plugins/range/automation/ansible.cfg) = /home/ec2-user/proj/plugins/range/automation/playbooks
```

##### OS / ENVIRONMENT
Amazon Linux (latest)

##### STEPS TO REPRODUCE
Create a configuration file with an AWS profile not defined in the default (`~/.aws/config`) profile and attempt to use it when executing a playbook.

`new-config-file`
```
[profile test-profile]
credential_source = Ec2InstanceMetadata
```

```yaml
- name: launch instance
  hosts: localhost
  tasks:
    - name: launch DC
      ec2:
        count: 1
        key_name: "{{ keypair }}"
        group_id: "{{ vpc_sg_ids }}"
        vpc_subnet_id: "{{ subnet.id }}"
        user_data: "{{ lookup('template', '../files/winrm.txt.j2') }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_windows }}"
        wait: yes
        region: "{{ region }}"
        assign_public_ip: yes
        validate_certs: no
```

```
$ AWS_CONFIG_FILE=new-config-file AWS_PROFILE=test-profile ansible-playbook test.yml
...
TASK [launch DC] ****************************************
fatal: [localhost]: FAILED! => changed=false
  msg: Profile given for AWS was not found.  Please fix and retry.

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=7    rescued=0    ignored=0
```

##### EXPECTED RESULTS
According to the [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html), the module should be able to use `AWS_CONFIG_FILE` to reference a custom configuration file instead of the default when looking for an AWS profile to use.

##### ACTUAL RESULTS
Ansible passes AWS_PROFILE as expected but ignores AWS_CONFIG_FILE. Ansible tries to reference `test-profile` from the default configuration instead of the configuration file specified.

```
$ AWS_CONFIG_FILE=new-config-file AWS_PROFILE=test-profile ansible-playbook test.yml
...
TASK [launch DC] ****************************************
fatal: [localhost]: FAILED! => changed=false
  msg: Profile given for AWS was not found.  Please fix and retry.

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=7    rescued=0    ignored=0
```
