### ISSUE TITLE
amazon.aws.elb_classic_lb does not support deletion_protection argument

### ISSUE THREAD

**Issue by stefanhorning** [ansible-collections/amazon.aws#2142]
### Summary

Unlike the other ELB modules the `elb_classic_lb` module does not support the `deletion_protection` argument.
This is somewhat inconsistent as this is a flag supported by all ELB types on AWS. So it would be nice to add it to the Ansible module too.
So one could add this line to all elb modules:
`deletion_protection: true`

Thank you for your consideration.

### Issue Type

Feature Idea

### Component Name

amazon.aws.elb_classic_lb

### Additional Information

```yaml
- name: Example ELB task
  amazon.aws.elb_classic_lb:
    name: 'my-classic-elb'
    scheme: internal
    security_group_ids: vpc-abc123
    listeners: [...]
    deletion_protection: true
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
