### ISSUE TITLE
State in ec2_instance is bypassed

### ISSUE THREAD

**Issue by rchassaigne** [ansible-collections/amazon.aws#2152]
### Summary

When I try to start, stop or restart an instance and set the state parameter, module want to create an instance

### Issue Type

Bug Report

### Component Name

ec2_instance

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.12]
  config file = None
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.16 (main, Apr 24 2024, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
Collection                    Version
----------------------------- -------
amazon.aws                    8.0.1
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /home/ec2-user/.local/lib/python3.9/site-packages
Requires:
Required-by:
---
Name: boto3
Version: 1.34.134
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /home/ec2-user/.local/lib/python3.9/site-packages
Requires: botocore, jmespath, s3transfer
Required-by:
---
Name: botocore
Version: 1.34.134
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /home/ec2-user/.local/lib/python3.9/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: boto3, s3transfer
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

### OS / Environment

amazon linux 2023

### Steps to Reproduce

```yaml (paste below)
---
- name: This playbook is used to stop the ec2 Instance
  hosts: localhost
  connection: local
  vars:
    instance_ids:
      - "i-***************"
  tasks:
    - name: restart a particular instance by its ID
      amazon.aws.ec2_instance:
        state: restarted
        instance_ids: "{{ instance_ids }}"
```

### Expected Results

Execute the state I wanted on the specific instance set in instance_ids

### Actual Results

```console (paste below)
fatal: [localhost]: FAILED! => {"changed": false, "msg": "You must include an image_id or image.id parameter to create an instance, or use a launch_template."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
