### ISSUE TITLE
Specify custom placement rule on bucket creation

### ISSUE THREAD

**Issue by Turgon37** [ansible-collections/amazon.aws#2214]
### Summary

Ansible module amazon.aws.s3_bucket say "Compatible with AWS, DigitalOcean, Ceph, Walrus, FakeS3 and StorageGRID" but it does not allow specify custom bucket placement rule

```
amazon.aws.s3_bucket:
  ceph: true
  name:  test03
  state: 'present'
  region: 'default:default-placement'

....
Couldn't connect to AWS: Provided region_name 'default:default-placement' doesn't match a supported format.
```

Ceph RGW supports to specify placement constraint using LocationContraint S3's api field

https://docs.ceph.com/en/latest/radosgw/placement/#s3-bucket-placement

```
<LocationConstraint>default:new-placement</LocationConstraint>
```

But amazon botocore does not allow this because of region name validation https://github.com/boto/botocore/blob/7f23afdfdbcab57e319a8d86622b4f0216fc7244/botocore/utils.py#L1315

I thinks it can be difficult to change the ceph caracter separator because it need to update all ceph cluster to take into account 
https://github.com/ceph/ceph/blob/08d2bd2b5efdaebc0553f4ca7bdd9d8c66423328/src/rgw/rgw_rest_s3.cc#L2521

Do you think we can ask botocore maintainer to allow disabling region name validation ?

### Issue Type

Bug Report

### Component Name

amazon.aws.s3_bucket

### Ansible Version

```console (paste below)
ansible-playbook [core 2.12.10]
  python version = 3.9.12 (main, Apr 19 2024, 15:53:37) [GCC 12.2.0]
  jinja version = 3.1.4
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
- name: community.aws
  version: 3.5.0
```

### AWS SDK versions

```console (paste below)
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /usr/local/lib/python3.9/site-packages
Requires: 
Required-by: 
---
Name: boto3
Version: 1.34.152
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: botocore, jmespath, s3transfer
Required-by: 
---
Name: botocore
Version: 1.34.152
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: boto3, s3transfer

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```
amazon.aws.s3_bucket:
  ceph: true
  name:  test03
  state: 'present'
  region: 'default:default-placement'
```

### Expected Results

bucket creation

### Actual Results

```
Couldn't connect to AWS: Provided region_name 'default:default-placement' doesn't match a supported format.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
