### ISSUE TITLE
How to use the ec2 module to start/stop exisiting EC2 instance

### ISSUE THREAD

**Issue by it-praktyk** [ansible-collections/amazon.aws#222]
##### SUMMARY

I'm not sure is it a request to explain/update documentation or the bug report.

I try to start/stop the existing EC2 instance using the `amazon.aws.ec2` module using the playbook like below.

```
---
- hosts: localhost
  gather_facts: false

  tasks:
    - local_action:
        module: amazon.aws.ec2
        instance_ids: ['i-07axxxxxxxxxxxxx7c']
        state: stopped
        region: eu-west-1
        wait: true
```

Because the `ansible-playbook` is run from the virtualenv I pass to it the value `-e 'ansible_python_interpreter=/home/<user_name>/Python-virtualenv/ansible-2.10.x/bin/python'

When I run it I receive only

```
TASK [amazon.aws.ec2] **********************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "wait for instances running timeout on Thu Dec 31 10:32:53 2020"}
```

The `ansible-inventory -i inventory_config_aws_ec2.yml --list`, run from the same virtualenv, returns the host that I try to stop.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
amazon.aws.ec2

##### ANSIBLE VERSION

```
ansible 2.10.4
  config file = /home/<folder_name>/ansible.cfg
  configured module search path = ['/home/<user_name>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<user_name>/Python-virtualenv/ansible-2.10.x/lib/python3.6/site-packages/ansible
  executable location = /home/<user_name>/Python-virtualenv/ansible-2.10.x/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

```
> ansible-galaxy collection list

# /home/<user_name>/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
amazon.aws        1.3.0  
ansible.netcommon 1.4.1  
```
