### ISSUE TITLE
8.1.0 fails with custom s3 provider (transfer acceleration feature)

### ISSUE THREAD

**Issue by johansenha** [ansible-collections/amazon.aws#2220]
### Summary

Since 8.1.0 s3_bucket module calls fail with an error even when transfer acceleration is set to false.
We are not using Amazon AWS S3 as endpoint but a custom one on-premises.

With 8.0.1 it's working without issues.

> s3_bucket - Add support for enabling Amazon S3 Transfer Acceleration by setting the accelerate_enabled option (https://github.com/ansible-collections/amazon.aws/pull/2046).

### Issue Type

Bug Report

### Component Name

s3_bucket

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.17.1]
  config file = /Users/user.name/git/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.8/dist-packages/ansible/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/10.1.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/user.name/git/collections:/Users/user.name/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/Cellar/ansible/10.1.0/libexec/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list

Collection                               Version
---------------------------------------- -------
amazon.aws                               8.1.0 
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore

Name: boto3
Version: 1.34.43

Name: botocore
Version: 1.34.43
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
Std configuration
```

### OS / Environment

Ubuntu

### Steps to Reproduce

```yaml (paste below)
- name: Create a bucket per customer
  amazon.aws.s3_bucket:
    endpoint_url: "https://{{ s3_endpoint_url }}"
    aws_access_key: "{{ s3_usage_accesskey }}"
    aws_secret_key: "{{ s3_usage_secretkey }}"
    name: "{{ item.name | lower }}"
    state: present
    tags:
      Owner: "{{ item.email }}"
  loop: "{{ customers }}"
```

### Expected Results

Bucket should be created

### Actual Results

```console (paste below)
  msg: 'Fetching bucket transfer acceleration state is not supported: An error occurred (NotImplemented) when calling the GetBucketAccelerateConfiguration operation: A header you provided implies functionality that is not implemented.'
  response_metadata:
    http_headers:
      connection: keep-alive
      content-length: '275'
      content-type: application/xml
      date: Mon, 19 Aug 2024 08:21:58 GMT
      server: S3
      strict-transport-security: max-age=31536000
      x-content-type-options: nosniff
      x-gmt-error-code: NotImplemented
      x-gmt-message: A header you provided implies functionality that is not implemented.
    http_status_code: 501
    retry_attempts: 0

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
