### ISSUE TITLE
amazon.aws.ec2_vol support on Multi-Attach

### ISSUE THREAD

**Issue by macklus** [ansible-collections/amazon.aws#225]
##### SUMMARY
AWS EC2 supports MultiAttach EBS disks (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volumes-multi.html) from 2020-02-20, but this feature is currently not available on ansible ec2_vol function.

##### ISSUE TYPE
Add support on ec2_vol function to:
- create multiattach disks
- attach a disk that its already attached on other server, if multiattach is enable.

##### COMPONENT NAME
amazon.aws.ec2_vol 

##### ADDITIONAL INFORMATION
- When create volume, adittional option should be possible, to specify if volume should be multiattach
- When attach, if volume has multiattach enable, and volume is already attached, error "Volume vol-xxxxxx is already attached to another instance: i-xxxx" should not appear

```yaml
- amazon.aws.ec2_vol:
    volume_size: 50
    volume_type: io1
    multi_attach: true
```
