### ISSUE TITLE
ec2_vol preserves Name Tag to None and removes other Tags from volume

### ISSUE THREAD

**Issue by jaudriga** [ansible-collections/amazon.aws#229]
##### SUMMARY
ec2_vol sets Name tag to `None` and removes all other Tags from volume.

It works when I use ansible 2.9 and `ec2_vol` instead of `amazon.aws.ec2_vol`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_vol

##### ANSIBLE VERSION
```
ansible 2.9.16
  config file = /home/ubuntu/user/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```
Also reproduced with ansible 2.10.

##### CONFIGURATION
```
INTERPRETER_PYTHON(/home/ubuntu/user/ansible.cfg) = auto
```

##### OS / ENVIRONMENT
```
    Virtualization: kvm
  Operating System: Ubuntu 20.04.1 LTS
            Kernel: Linux 5.4.0-1034-aws
      Architecture: x86-64
# dpkg -l | grep boto
ii  python3-boto                         2.49.0-2.1                        all          Python interface to Amazon's Web Services - Python 3.x
ii  python3-boto3                        1.9.253-1                         all          Python interface to Amazon's Web Services - Python 3.x
ii  python3-botocore                     1.16.19+repack-1ubuntu0.20.04.1   all          Low-level, data-driven core of boto 3 (Python 3)
```
I am using amazon.aws version 1.3.0

##### STEPS TO REPRODUCE
Run the following from an ec2 machine with a volume that has the appropriate tags.
```
- name: Get ec2 instance facts
  amazon.aws.ec2_metadata_facts:

- name: Get available volumes 
  amazon.aws.ec2_vol_info: 
    filters:
      status: available
      availability-zone: "{{ ansible_ec2_placement_availability_zone }}"
      tag:Instance: "{{ server_type }}*"
      tag:Service: "{{ service_type }}"
      tag:Environment: "{{ env }}"
    region: "{{ ansible_ec2_placement_region }}"
  register: available_volumes
    
- name: Attach volume
  amazon.aws.ec2_vol:
    id: "{{ available_volumes.volumes[0].id }}"
    instance: "{{ ansible_ec2_instance_id }}"
    device_name: "{{ attach_volume_name }}"
    region: "{{ ansible_ec2_placement_region }}"
```

##### EXPECTED RESULTS
Tags should be left alone.
```
TASK [attach_volume : Get available volumes] *************************************************************************************************************************************************
task path: /home/ubuntu/user/roles/attach_volume/tasks/aws.yml:32
ok: [localhost] => {"changed": false, "volumes": [{"attachment_set": {"attach_time": null, "delete_on_termination": null, "device": null, "instance_id": null, "status": null}, "create_time": "2020-05-26T15:24:55.813000+00:00", "encrypted": true, "id": "vol-0c994ca3a7d01bad6", "iops": 100, "region": "eu-west-1", "size": 8, "snapshot_id": "", "status": "available", "tags": {"Environment": "exp", "Instance": "monitoring", "IsMaster": "master", "Name": "grafana-data", "Role": "LOMO", "Service": "grafana"}, "type": "gp2", "zone": "eu-west-1b"}]}

TASK [attach_volume : Attach volume] *********************************************************************************************************************************************************
task path: /home/ubuntu/user/roles/attach_volume/tasks/aws.yml:44
changed: [localhost] => {"changed": true, "device": "/dev/sdf", "volume": {"attachment_set": {"attach_time": "2021-01-07T13:50:34.000Z", "deleteOnTermination": "false", "device": "/dev/sdf", "instance_id": "i-0b09f6d53dbac581f", "status": "attached"}, "create_time": "2020-05-26T15:24:55.813Z", "encrypted": true, "id": "vol-0c994ca3a7d01bad6", "iops": 100, "size": 8, "snapshot_id": "", "status": "in-use", "tags": {"Environment": "exp", "Instance": "monitoring", "IsMaster": "master", "Name": "grafana-data", "Role": "LOMO", "Service": "grafana"}, "type": "gp2", "zone": "eu-west-1b"}, "volume_id": "vol-0c994ca3a7d01bad6", "volume_type": "gp2"}
```

##### ACTUAL RESULTS
Tags get changed:
```
TASK [attach_volume : Get available volumes] *************************************************************************************************************************************************
task path: /home/ubuntu/user/roles/attach_volume/tasks/aws.yml:32
ok: [localhost] => {"changed": false, "volumes": [{"attachment_set": {"attach_time": null, "delete_on_termination": null, "device": null, "instance_id": null, "status": null}, "create_time": "2020-05-26T15:24:55.813000+00:00", "encrypted": true, "id": "vol-0c994ca3a7d01bad6", "iops": 100, "region": "eu-west-1", "size": 8, "snapshot_id": "", "status": "available", "tags": {"Environment": "exp", "Instance": "monitoring", "IsMaster": "master", "Name": "grafana-data", "Role": "LOMO", "Service": "grafana"}, "type": "gp2", "zone": "eu-west-1b"}]}

TASK [attach_volume : Attach volume] *********************************************************************************************************************************************************
task path: /home/ubuntu/user/roles/attach_volume/tasks/aws.yml:44
changed: [localhost] => {"changed": true, "device": "/dev/sdf", "volume": {"attachment_set": {"attach_time": "2021-01-07T08:36:52+00:00", "deleteOnTermination": false, "device": "/dev/sdf", "instance_id": "i-0bdb31471ad654d66", "status": "attaching"}, "create_time": "2020-05-26T15:24:55.813000+00:00", "encrypted": true, "id": "vol-0c994ca3a7d01bad6", "iops": 100, "size": 8, "snapshot_id": "", "status": "in-use", "tags": {"Name": "None"}, "type": "gp2", "zone": "eu-west-1b"}, "volume_id": "vol-0c994ca3a7d01bad6", "volume_type": "gp2"}
```
