### ISSUE TITLE
ec2_instance fails when trying to run instance using a launch template without a defined default subnet

### ISSUE THREAD

**Issue by abikouo** [ansible-collections/amazon.aws#2321]
### Summary

When trying to run instance using a launch template in an AWS environment where no default subnet is defined, the module fails with the following message 

```shell
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No default subnet could be found - you must include a VPC subnet ID (vpc_subnet_id parameter)."}
```

### Issue Type

Bug Report

### Component Name

ec2_instance

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
   - name: Create launch template
      community.aws.ec2_launch_template:
        template_name: "my-testing-template"
        instance_type: t2.micro
        image_id: "{{ vm_image_id }}"
        network_interfaces:
          - device_index: 0
            associate_public_ip_address: false
            delete_on_termination: true
            subnet_id: "{{ my_subnet_id }}"
            private_ip_address: "10.1.8.11"
      register: _create_template

    - name: Create EC2 instance using launch template
      amazon.aws.ec2_instance:
        state: present
        wait: true
        launch_template:
          name: "{{ _create_template.template.launch_template_id }}"
```

### Expected Results

The module should succeed

### Actual Results

```console (paste below)
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No default subnet could be found - you must include a VPC subnet ID (vpc_subnet_id parameter)."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
