### ISSUE TITLE
Add s3 object tagging support

### ISSUE THREAD

**Issue by QCU87Z** [ansible-collections/amazon.aws#233]
##### SUMMARY

Currently I can not see away to add tags to S3 objects. The project I am on requires this feature

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

amazon.aws.aws_s3

##### ADDITIONAL INFORMATION

There should be another paramater for the amazon.aws.aws_s3 task that allows to you pass a dict of tags and their values

```yaml
- name: upload s3 boject
  amazon.aws.aws_s3
    bucket: input-bucket
    object: newObject
    src: files/object
    tags:
      - tag1: value1
      - tag2: value 2
```
Or something like that
