### ISSUE TITLE
AWS inverse filter in Ansible 2.10.5 amazon aws ec2.py causing bad return and empty array during stop task. 

### ISSUE THREAD

**Issue by IamNobleSix** [ansible-collections/amazon.aws#235]
##### SUMMARY
In PR https://github.com/ansible-collections/amazon.aws/pull/197/files there was an addition to ec2.py which added an inverse lookup to remove terminated and shutting-down instances from the instance-state-name filter. To the best of my knowledge, aws ec2 filters do not support inverse filters. This is causing a bad return from aws ec2, which removes all hosts from the actionable command. 

Our ec2 instance stop playbook broke when moving from ansible 2.10.4 to 2.10.5, and the file diff showed the filter line as the only impacting change in ec2.py. By removing this inverse filter the playbooks worked again. This is the diff between the working ec2.py and NOT working ec2.py

```
Desktop:$ diff working_ec2_py.txt broken_ec2_py.txt
1418a1419,1420
>     filters['instance-state-name'] = ["!terminated", "!shutting-down"]
>
1739d1740
<
Desktop:$
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
amazon aws ec2 module

##### ANSIBLE VERSION

```
~:$ ansible --version
ansible 2.10.4
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.10.5/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Jan  8 2021, 17:17:17) [Clang 12.0.0 (clang-1200.0.32.28)]
```

##### CONFIGURATION

```
~:$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT
macOS Catalina 10.15.7

##### STEPS TO REPRODUCE

Use 2.10.4 amazon aws ec2.py module and attempt to stop a running instance. Then use 2.10.5 amazon aws ec2.py module and try again. We are simply providing an instance_id via our inventory for the stop. 

```yaml
  - name: Check if Instance is already Stopped
    delegate_to: 127.0.0.1
    ec2_instance_info:
      validate_certs: no
      aws_access_key: "{{ aws_access_key | default(omit) }}"
      aws_secret_key: "{{ aws_secret_key | default(omit) }}"
      region: "{{ aws_region }}"
      instance_ids: "{{ instance_id }}"
    register: ec2_instance_state

- name: Save the Instance State
    set_fact:
      ec2_instance_state: "{{ ec2_instance_state.instances[0].state.name }}"

- name: Stop AWS EC2 Instance
    when: ec2_instance_state != "stopped"
    delegate_to: 127.0.0.1
    ec2:
      validate_certs: no
      aws_access_key: "{{ aws_access_key | default(omit) }}"
      aws_secret_key: "{{ aws_secret_key | default(omit) }}"
      region: "{{ aws_region }}"
      instance_ids: "{{ instance_id }}"
      state: stopped
    register: ec2_instance_status
```

##### EXPECTED RESULTS
Using the 2.10.4 ec2.py module these are the working results:

```
  PLAYHOST done: {
    "changed": true,
    "instance_ids": [
        "i-08.......ee9f"
    ],
    "instances": [
        {
            "ami_launch_index": "0",
            "architecture": "x86_64",
            "block_device_mapping": {
                "/dev/sda1": {
                    "delete_on_termination": true,
                    "status": "attached",
                    "volume_id": "vol-0........a80"
                },
                "/dev/sdb": {
                    "delete_on_termination": false,
                    "status": "attached",
                    "volume_id": "vol-0.........47e"
                }
            },
            "dns_name": "",
            "ebs_optimized": true,
            "groups": {
                "<redacted>"
            },
            "hypervisor": "xen",
            "id": "i-08........ee9f",
            "image_id": "<redacted>",
            "instance_type": "m5.large",
            "kernel": null,
            "key_name": "<redacted>",
            "launch_time": "2021-01-14T16:48:56.000Z",
            "placement": "us-east-1a",
            "private_dns_name": "<redacted>",
            "private_ip": "<redacted>",
            "public_dns_name": "",
            "public_ip": null,
            "ramdisk": null,
            "region": "us-east-1",
            "root_device_name": "/dev/sda1",
            "root_device_type": "ebs",
            "state": "running",
            "state_code": 16,
            "tags": {
                "<redacted>"
            },
            "tenancy": "default",
            "virtualization_type": "hvm"
        }
    ],
    "invocation": {
        "module_args": {
```

##### ACTUAL RESULTS
Note the empty instances array, and changed:false, using the 2.10.5 ec2.py with the inverse filter line in the code. 

```
PLAYHOST ok: {
    "changed": false,
    "instance_ids": [
        "i-08..........ee9f"
    ],
    "instances": [],
    "invocation": {
        "module_args": {
```

Ultimately no action is ever taken on the instance, so it is never stopped. There are no playbook or inventory changes. Just removing the 1 line of code.
