### ISSUE TITLE
Manage S3 lifecycle configurations with s3_bucket

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible-collections/amazon.aws#244]
##### SUMMARY

I would like to apply a bucket lifecycle configuration with `s3_bucket`.

My specific use case is configuring the bucket to abort abandoned multi-part uploads.
(Otherwise you can end up paying for storage of data which is not visible in the bucket.)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
s3_bucket

##### ADDITIONAL INFORMATION

The bucket policy itself is supposed to be xml.

```
- amazon.aws.s3_bucket:
    name: mys3bucket
    state: present
    lifecycle_configuration:
        rules:
        - id: sample-rule</ID>
          status: Enabled
          AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
```

I'm unsure whether the module should use the same capitalisation as the API (`AbortIncompleteMultipartUpload`), or if we should rename to be consistent with Ansible (`abort_incomplete_multipart_upload`) and then convert it.
I suspect using CamelCase would be better.
