### ISSUE TITLE
Add prefix parameter in s3_object_info module to list S3 objects under a specific prefix

### ISSUE THREAD

**Issue by mredouin** [ansible-collections/amazon.aws#2477]
### Summary

As the support for list has been deprecated in s3_object module (and will be removed), I was looking for a way to list the content of a S3 bucket under a specific prefix.
I did not find this option in s3_object_info module.

### Issue Type

Feature Idea

### Component Name

amazon.aws.s3_object_info

### Additional Information

S3bucket , aws_region, prefix are defined beforehand.
Access keys and secret has been defined to access the S3 bucket.

```yaml (paste below)
- name: "List {{ S3bucket }} S3 bucket content under {{ prefix }}"
  amazon.aws.s3_object_info:
    bucket_name: "{{ S3bucket }}"
    region: "{{ aws_region }}"
    prefix: "{{ prefix }}"
  register: S3bucket_list_result

- name: "Display the list of objects"
  ansible.builtin.debug:
    msg: "{{ S3bucket_list_result.s3_keys }}"
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
