### ISSUE TITLE
Create directories with metadata

### ISSUE THREAD

**Issue by aborche** [ansible-collections/amazon.aws#2528]
### Summary

Base method 'create' of amazon.aws.s3_object does not support change folders metadata for new folder.
And, for example on Minio, when we use it with s3fs, all folders got permissions '0750' and owner 'root'.
After mounting these folders into container, with other id than root, we always get error 'Access denied'.

a simple patch(below) resolves this issue

```
--- lib/python3.12/site-packages/ansible_collections/amazon/aws/plugins/modules/s3_object.py	2025-02-17 21:05:13.180880958 +0300
+++ s3_object.py	2025-02-17 21:13:00.969246386 +0300
@@ -629,7 +629,7 @@
         raise S3ObjectFailure(f"Failed while creating object {obj}.", e)
 
 
-def create_dirkey(module, s3, bucket, obj, encrypt, expiry):
+def create_dirkey(module, s3, bucket, obj, encrypt, expiry, metadata):
     if module.check_mode:
         module.exit_json(msg="PUT operation skipped - running in check mode", changed=True)
     params = {"Bucket": bucket, "Key": obj, "Body": b""}
@@ -638,6 +638,7 @@
             encrypt,
             module.params.get("encryption_mode"),
             module.params.get("encryption_kms_key_id"),
+            metadata,
         )
     )
     put_object_acl(module, s3, bucket, obj, params)
@@ -1154,6 +1155,7 @@
         s3_vars["object"],
         s3_vars["encrypt"],
         s3_vars["expiry"],
+        s3_vars["metadata"],
     )
```

Can you include this patch into new release? Because patching running tree of ansible collection is not a good way.

### Issue Type

Feature Idea

### Component Name

amazon.aws.s3_object

### Additional Information

```yaml
  - name: Create directories
    aws_s3:
      endpoint_url: "{{ S3FS_URL }}"
      bucket: "{{ S3FS_BUCKET }}"
      object: "{{ item }}"
      mode: create
      encrypt: false
      validate_certs: false
      metadata:
        mode: "16877"
        acl: "public-read"
        gid: "2"
        uid: "2"
    with_items:
      - "{{ S3FS_FOLDER }}"
      - "{{ S3FS_FOLDER }}/public"
      - "{{ S3FS_FOLDER }}/preview"
      - "{{ S3FS_FOLDER }}/private"
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
