### ISSUE TITLE
Separate DocumentDB from rds_cluster/rds_instance module into seperate DocumentDB module

### ISSUE THREAD

**Issue by randoneering** [ansible-collections/amazon.aws#2532]
### Summary

When using the rds_cluster or rds_instance modules in an account where there are DocumentDB clusters present, the DocumentDB clusters are grabbed by both and their related functions (info, modify, etc). To work around this, we have filtered out the DocumentDB clusters as they use different parameter sets than rds clusters and instances. I will provide an example of the filtering we use (as there are many other ways to do it, I am sure) in the fields below. 

I would like to purpose that a separate plugin/set of modules are created for DocumentDB clusters and instances. 

Below is the documentation for DocDB in boto3

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/docdb.html

### Issue Type

Feature Idea

### Component Name

docdb_instance,docdb_cluster,docdb_cluster_info,docdb_instance_info, etc

### Additional Information

```yaml (paste below)

---
- name: Enforce Database Settings
  hosts: all
  vars:
    env_xx_cluster: "[?tags.environment == 'xx'].db_cluster_identifier"
    env_xx_cluster_instance: "[?tags.environment == 'xx'].db_cluster_members[].db_instance_identifier"
    env_xx_instance: "[?tags.environment == 'xx'].db_instance_identifier"
    channel_email: something@something.com
  tasks:
    - name: connect to xx account
      amazon.aws.sts_assume_role:
        region: us-east-1
        role_arn: "arn:aws:iam::123412351:role/role"
        role_session_name: "enforce_settings"
      register: assumed_role_xx
    
    - name: get xx rds instance details
      amazon.aws.rds_instance_info:
        region: us-east-1
        access_key: "{{ assumed_role_xx.sts_creds.access_key }}"
        secret_key: "{{ assumed_role_xx.sts_creds.secret_key }}"
        session_token: "{{ assumed_role_xx.sts_creds.session_token }}"
      register: xx_instance

    - name: filter out docdb and aurora engines in instances
      ansible.builtin.set_fact:
        xx_instances: "{{ xx_instance.instances | selectattr('engine', 'search', '^(?!aurora|docdb)') }}"
            
    - name: filter out stopped instances
      ansible.builtin.set_fact: 
        xx_instances_avail: "{{ xx_instances | selectattr('db_instance_status', 'eq', 'available') }}"
      
    - name: get xx rds cluster details
      amazon.aws.rds_cluster_info:
        region: us-east-1
        access_key: "{{ assumed_role_xx.sts_creds.access_key }}"
        secret_key: "{{ assumed_role_xx.sts_creds.secret_key }}"
        session_token: "{{ assumed_role_xx.sts_creds.session_token }}"
      register: xx_cluster

    - name: filter out docdb in clusters
      ansible.builtin.set_fact:
        xx_clusters: "{{ xx_cluster.clusters | selectattr('engine', 'search', 'aurora') }}"

    - name: filter out stopped clusters
      ansible.builtin.set_fact: 
        xx_clusters_avail: "{{ xx_clusters | selectattr('status', 'eq', 'available') }}"

    - name: get xx rds cluster instance details
      amazon.aws.rds_cluster_info:
        region: us-east-1
        access_key: "{{ assumed_role_xx.sts_creds.access_key }}"
        secret_key: "{{ assumed_role_xx.sts_creds.secret_key }}"
        session_token: "{{ assumed_role_xx.sts_creds.session_token }}"
      register: xx_cluster_instance

    - name: filter out docdb in cluster instances
      ansible.builtin.set_fact:
        xx_cluster_instances: "{{ xx_cluster_instance.clusters | selectattr('engine', 'search', 'aurora') }}"

......
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
