### ISSUE TITLE
elb_application_lb fails with multiple DefaultActions

### ISSUE THREAD

**Issue by fabricat-mdb** [ansible-collections/amazon.aws#2537]
### Summary

`elb_application_lb` module fails if the parameter `DefaultActions` has more than one item.

### Workaround
To avoid failure, I'm using `_sort_actions` instead of `_sort_listener_actions` in [elbv2.py](/plugins/module_utils/elbv2.py#L798-801).
`_sort_actions` simply uses `Order` as the sorting key. I noticed that `Order` is always present in `current_listener`, and [is required](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elbv2/client/create_listener.html) in module parameters when the listener has more than one default action.
When there is only one default action, sorting is irrelevant.

Now, the module does not fail anymore, but it always returns as "changed" (similar to issue #1284).
This is probably related to `Order` being defaulted to 0 instead of 1 [here](/plugins/module_utils/elbv2.py#L159), and/or to `AuthenticateOidcConfig.ClientSecret` being not returned in the [AuthenticateOidcActionConfig](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_AuthenticateOidcActionConfig.html) object.

### Issue Type

Bug Report

### Component Name

elb_application_lb

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.7]
  config file = /Users/fab/workdir/ansible/ansible.cfg
  configured module search path = ['/Users/fab/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible@10/10.7.0_1/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/fab/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/opt/ansible@10/bin/ansible
  python version = 3.12.9 (main, Feb  4 2025, 14:38:38) [Clang 16.0.0 (clang-1600.0.26.6)] (/opt/homebrew/Cellar/ansible@10/10.7.0_1/libexec/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list

# /Users/fab/.ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
amazon.aws                               9.2.0
ansible.posix                            2.0.0
community.aws                            9.0.0
community.general                        10.4.0
prometheus.prometheus                    0.19.0

# /opt/homebrew/Cellar/ansible@10/10.7.0_1/libexec/lib/python3.12/site-packages/ansible_collections
Collection                               Version
---------------------------------------- -------
amazon.aws                               8.2.1
ansible.netcommon                        6.1.3
ansible.posix                            1.6.2
ansible.utils                            4.1.0
ansible.windows                          2.5.0
arista.eos                               9.0.0
awx.awx                                  24.6.1
azure.azcollection                       2.7.0
check_point.mgmt                         5.2.3
chocolatey.chocolatey                    1.5.3
cisco.aci                                2.10.1
cisco.asa                                5.0.1
cisco.dnac                               6.25.0
cisco.intersight                         2.0.20
cisco.ios                                8.0.0
cisco.iosxr                              9.0.0
cisco.ise                                2.9.6
cisco.meraki                             2.18.3
cisco.mso                                2.9.0
cisco.nxos                               8.1.0
cisco.ucs                                1.14.0
cloud.common                             3.0.0
cloudscale_ch.cloud                      2.4.0
community.aws                            8.0.0
community.ciscosmb                       1.0.9
community.crypto                         2.22.3
community.digitalocean                   1.27.0
community.dns                            3.1.0
community.docker                         3.13.3
community.general                        9.5.2
community.grafana                        1.9.1
community.hashi_vault                    6.2.0
community.hrobot                         2.0.2
community.library_inventory_filtering_v1 1.0.2
community.libvirt                        1.3.0
community.mongodb                        1.7.8
community.mysql                          3.11.0
community.network                        5.1.0
community.okd                            3.0.1
community.postgresql                     3.9.0
community.proxysql                       1.6.0
community.rabbitmq                       1.3.0
community.routeros                       2.20.0
community.sap_libs                       1.4.2
community.sops                           1.9.1
community.vmware                         4.8.1
community.windows                        2.3.0
community.zabbix                         2.5.1
containers.podman                        1.16.2
cyberark.conjur                          1.3.1
cyberark.pas                             1.0.30
dellemc.enterprise_sonic                 2.5.1
dellemc.openmanage                       9.9.0
dellemc.powerflex                        2.5.0
dellemc.unity                            2.0.0
f5networks.f5_modules                    1.32.1
fortinet.fortimanager                    2.8.2
fortinet.fortios                         2.3.8
frr.frr                                  2.0.2
google.cloud                             1.4.1
grafana.grafana                          5.6.0
hetzner.hcloud                           3.1.1
ibm.qradar                               3.0.0
ibm.spectrum_virtualize                  2.0.0
ibm.storage_virtualize                   2.5.0
ieisystem.inmanage                       2.0.0
infinidat.infinibox                      1.4.5
infoblox.nios_modules                    1.7.1
inspur.ispim                             2.2.3
inspur.sm                                2.3.0
junipernetworks.junos                    8.0.0
kaytus.ksmanage                          1.2.2
kubernetes.core                          3.2.0
kubevirt.core                            1.5.0
lowlydba.sqlserver                       2.3.4
microsoft.ad                             1.7.1
netapp.cloudmanager                      21.24.0
netapp.ontap                             22.13.0
netapp.storagegrid                       21.13.0
netapp_eseries.santricity                1.4.1
netbox.netbox                            3.20.0
ngine_io.cloudstack                      2.5.0
ngine_io.exoscale                        1.1.0
openstack.cloud                          2.3.0
openvswitch.openvswitch                  2.1.1
ovirt.ovirt                              3.2.0
purestorage.flasharray                   1.32.0
purestorage.flashblade                   1.19.1
sensu.sensu_go                           1.14.0
splunk.es                                3.0.0
t_systems_mms.icinga_director            2.0.1
telekom_mms.icinga_director              2.2.1
theforeman.foreman                       4.2.0
vmware.vmware                            1.7.1
vmware.vmware_rest                       3.2.0
vultr.cloud                              1.13.0
vyos.vyos                                4.1.0
wti.remote                               1.0.10
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
WARNING: Package(s) not found: boto
Name: boto3
Version: 1.34.109
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /Users/fabrizio.catalucci/Library/Python/3.12/lib/python/site-packages
Requires: botocore, jmespath, s3transfer
Required-by:
---
Name: botocore
Version: 1.34.109
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /Users/fabrizio.catalucci/Library/Python/3.12/lib/python/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: boto3, s3transfer
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CACHE_PLUGIN(/Users/fab/workdir/ansible/ansible.cfg) = ansible.builtin.jsonfile
CACHE_PLUGIN_CONNECTION(/Users/fab/workdir/ansible/ansible.cfg) = /tmp/ansible_facts
CALLBACKS_ENABLED(/Users/fab/workdir/ansible/ansible.cfg) = ['community.general.log_plays']
CONFIG_FILE() = /Users/fab/workdir/ansible/ansible.cfg
DEFAULT_GATHERING(/Users/fab/workdir/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/Users/fab/workdir/ansible/ansible.cfg) = ['/Users/fab/workdir/ansible/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/Users/fab/workdir/ansible/ansible.cfg) = True
DEFAULT_MANAGED_STR(/Users/fab/workdir/ansible/ansible.cfg) = Managed by Ansible (10gen/itproductivity-ansible).
INTERPRETER_PYTHON(/Users/fab/workdir/ansible/ansible.cfg) = auto_silent
INVENTORY_CACHE_ENABLED(/Users/fab/workdir/ansible/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/Users/fab/workdir/ansible/ansible.cfg) = ansible.builtin.jsonfile
INVENTORY_CACHE_PLUGIN_CONNECTION(/Users/fab/workdir/ansible/ansible.cfg) = /tmp/ansible_inventory
MAX_FILE_SIZE_FOR_DIFF(/Users/fab/workdir/ansible/ansible.cfg) = 1048576
TRANSFORM_INVALID_GROUP_CHARS(/Users/fab/workdir/ansible/ansible.cfg) = always
```

### OS / Environment

macOS 15.3.1

### Steps to Reproduce

```yaml (paste below)
- name: POC
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Create ALB
      amazon.aws.elb_application_lb:
        name: bug-poc
        scheme: internal
        listeners:
          - Protocol: HTTPS
            Port: 443
            DefaultActions:
              - Type: authenticate-oidc
                Order: 1
                AuthenticateOidcConfig:
                  Issuer: "https://okta.example.com"
                  AuthorizationEndpoint: "https://okta.example.com/oauth2/v1/authorize"
                  TokenEndpoint: "https://okta.example.com/oauth2/v1/token"
                  UserInfoEndpoint: "https://okta.example.com/oauth2/v1/userinfo"
                  ClientId: fake123
                  ClientSecret: fake456
                  SessionCookieName: AWSELBAuthSessionCookie
                  Scope: openid
                  SessionTimeout: 604800
                  OnUnauthenticatedRequest: authenticate
              - Type: fixed-response
                Order: 2
                FixedResponseConfig:
                  ContentType: text/plain
                  MessageBody: Not available
                  StatusCode: "404"
            Certificates:
              - CertificateArn: "arn:aws:acm:us-east-1:123456789012:certificate/4843cf86-bd8d-4cb4-a03c-27fe4680ba31"
            SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
        security_groups: []
        subnets:
          - subnet-00112233445566778
          - subnet-00112233445566779
```

### Expected Results

```console
PLAY [POC] *************************************************************************************************************************************************************************

TASK [Create ALB] ******************************************************************************************************************************************************************
changed (or ok): [localhost]
```

### Actual Results

```console (paste below)
PLAY [POC] *************************************************************************************************************************************************************************

TASK [Create ALB] ******************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: '<' not supported between instances of 'dict' and 'NoneType'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/fab/.ansible/tmp/ansible-tmp-1740589907.356226-34108-280154655960551/AnsiballZ_elb_application_lb.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/Users/fab/.ansible/tmp/ansible-tmp-1740589907.356226-34108-280154655960551/AnsiballZ_elb_application_lb.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/fab/.ansible/tmp/ansible-tmp-1740589907.356226-34108-280154655960551/AnsiballZ_elb_application_lb.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.amazon.aws.plugins.modules.elb_application_lb', init_globals=dict(_module_fqn='ansible_collections.amazon.aws.plugins.modules.elb_application_lb', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/folders/4d/j1qvv2mn3hb3zcvw97k58hd80000gp/T/ansible_amazon.aws.elb_application_lb_payload_7oop3xd4/ansible_amazon.aws.elb_application_lb_payload.zip/ansible_collections/amazon/aws/plugins/modules/elb_application_lb.py\", line 1060, in <module>\n  File \"/var/folders/4d/j1qvv2mn3hb3zcvw97k58hd80000gp/T/ansible_amazon.aws.elb_application_lb_payload_7oop3xd4/ansible_amazon.aws.elb_application_lb_payload.zip/ansible_collections/amazon/aws/plugins/modules/elb_application_lb.py\", line 1052, in main\n  File \"/var/folders/4d/j1qvv2mn3hb3zcvw97k58hd80000gp/T/ansible_amazon.aws.elb_application_lb_payload_7oop3xd4/ansible_amazon.aws.elb_application_lb_payload.zip/ansible_collections/amazon/aws/plugins/modules/elb_application_lb.py\", line 860, in create_or_update_alb\n  File \"/var/folders/4d/j1qvv2mn3hb3zcvw97k58hd80000gp/T/ansible_amazon.aws.elb_application_lb_payload_7oop3xd4/ansible_amazon.aws.elb_application_lb_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/elbv2.py\", line 933, in compare_listeners\n  File \"/var/folders/4d/j1qvv2mn3hb3zcvw97k58hd80000gp/T/ansible_amazon.aws.elb_application_lb_payload_7oop3xd4/ansible_amazon.aws.elb_application_lb_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/elbv2.py\", line 865, in _group_listeners\n  File \"/var/folders/4d/j1qvv2mn3hb3zcvw97k58hd80000gp/T/ansible_amazon.aws.elb_application_lb_payload_7oop3xd4/ansible_amazon.aws.elb_application_lb_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/elbv2.py\", line 807, in _compare_listener\n  File \"/var/folders/4d/j1qvv2mn3hb3zcvw97k58hd80000gp/T/ansible_amazon.aws.elb_application_lb_payload_7oop3xd4/ansible_amazon.aws.elb_application_lb_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/elbv2.py\", line 163, in _sort_listener_actions\nTypeError: '<' not supported between instances of 'dict' and 'NoneType'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
