### ISSUE TITLE
does tags key support jinja2 templating?

### ISSUE THREAD

**Issue by mator** [ansible-collections/amazon.aws#2541]
### Summary

Hello!

Does "amazon.aws.ec2_instance" module support of using jinja2 templating in tags key/names?

The sample code is below.

### Issue Type

Bug Report

### Component Name

ec2_instance

### Ansible Version

``` 
$ ansible --version
ansible [core 2.18.3]
  config file = /Users/anatoliip/ansible.aws/ansible.cfg
  configured module search path = ['/Users/anatoliip/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/11.3.0/libexec/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/anatoliip/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)] (/opt/homebrew/Cellar/ansible/11.3.0/libexec/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Collection Versions

```
% ansible-galaxy collection list  | head

# /Users/anatoliip/.ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
amazon.aws                               9.2.0

# /opt/homebrew/Cellar/ansible/11.3.0/libexec/lib/python3.13/site-packages/ansible_collections
Collection                               Version
---------------------------------------- -------
amazon.aws                               9.2.0
```

### AWS SDK versions

```
% find /opt/homebrew/Cellar/ansible/11.3.0/ -name boto\*
/opt/homebrew/Cellar/ansible/11.3.0//libexec/lib/python3.13/site-packages/botocore-1.37.1.dist-info
/opt/homebrew/Cellar/ansible/11.3.0//libexec/lib/python3.13/site-packages/boto3-1.37.1.dist-info
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_NOCOLOR(/Users/anatoliip/ansible.aws/ansible.cfg) = True
CONFIG_FILE() = /Users/anatoliip/ansible.aws/ansible.cfg
```

### OS / Environment

MacOS 14.6.1

### Steps to Reproduce

```
% cat debug-tags.yaml
---
- name: Debug tags
  hosts: localhost
  gather_facts: false
  vars_files: vars/regional_settings
  vars:
    env_name: "production"
    app_version: "v1.2.3"
    tag_prefix: "App"
  tasks:
    - name: Launch EC2 instance with templated tag keys
      amazon.aws.ec2_instance:
        name: "tag test"
        key_name: your_key_name
        instance_type: t3.micro
        region: "{{ region }}"
        image_id: ami-xxxxxxxxx
        tags:
          "{{ tag_prefix }}_Environment": "{{ env_name }}"
          "{{ tag_prefix }}_Version": "{{ app_version }}"
      register: ec2

    - name: Print the tags created
      ansible.builtin.debug:
        msg: "{{ ec2.instances[0].tags }}"
```

### Expected Results

expected VM (ec2 instance) to be created with proper tags, i.e. 
```
ok: [localhost] => {
    "msg": {
        "Name": "tag test",
        "App_Environment": "production",
        "App_Version": "v1.2.3"
    }
}
```

### Actual Results

running playbook:
```
% ansible-playbook debug-tags.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Debug tags] *************************************************************************************************

TASK [Launch EC2 instance with templated tag keys] *************************************************************************************************
changed: [localhost]

TASK [Print the tags created] **********************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "Name": "tag test",
        "{{ tag_prefix }}_Environment": "production",
        "{{ tag_prefix }}_Version": "v1.2.3"
    }
}

PLAY RECAP *****************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
```


### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by tremble** [comment]
Thanks for taking the time to open this issue.

The templating of parameters for modules is actually done at the "ansible-core" level, and is not handled in the collections themselves.  The underlying issue here is actually a design decision of Ansible itself:  https://github.com/ansible/ansible/issues/17324#issuecomment-685102595

> We purposefully do not template dictionary keys. We only template values. This is a conscious decision, and we have no plans to change this behavior.

You'll find the same behaviour with `ansible.builtin.set_fact`:

```
- hosts: localhost
  gather_facts: false
  vars:
    env_name: "production"
    app_version: "v1.2.3"
    tag_prefix: "App"
  tasks:
    - name: Set a fact to test behaviour
      set_fact:
        tags:
            "{{ tag_prefix }}_Environment": "{{ env_name }}"
            "{{ tag_prefix }}_Version": "{{ app_version }}"

    - name: Print generated fact
      ansible.builtin.debug:
        msg: "{{ tags }}"
```

There are some hacks by doing things like passing a templated JSON **string** that represents a dictionary instead of a dictionary directly, however given the upstream design decision, it's risky to rely on these:

```
- hosts: localhost
  gather_facts: false
  vars:
    env_name: "production"
    app_version: "v1.2.3"
    tag_prefix: "App"
  tasks:
    - name: Set a fact to test behaviour
      set_fact:
        stringed_tags: "{
          '{{ tag_prefix }}_Environment': '{{ env_name }}',
          '{{ tag_prefix }}_Version': '{{ app_version }}'
        }"
    - name: Print generated fact
      ansible.builtin.debug:
        msg: "{{ stringed_tags }}"
```
