### ISSUE TITLE
[ec2_vpc_vpn] Doesn't allow TunnelInsideCidr without TunnelInsideIpv6Cidr but AWS returns InvalidParameterCombination

### ISSUE THREAD

**Issue by DandyDeveloper** [ansible-collections/amazon.aws#2546]
### Summary

Trying to create a VPN connection with 

```
  amazon.aws.ec2_vpc_vpn:
    state: present
    vpn_gateway_id: "{{ vgw.vgw.id }}"
    customer_gateway_id: "{{ cgw.gateway.customer_gateway.customer_gateway_id }}"
    static_only: true
    tunnel_options:
    - PreSharedKey: "{{ peer_passphrase }}"
      TunnelInsideCidr: "x.x.x.x/x"
      TunnelInsideIpv6Cidr: ""
    - PreSharedKey: "{{ peer_passphrase }}"
      TunnelInsideCidr: "x.x.x.x/x"
...
```

Results in: 

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter Options.TunnelOptions[1].TunnelInsideIpv6Cidr, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

However, including the `TunnelInsideIpv6Cidr` to the tunnel options then gives the following error:

> : Failed to create vpn connection: An error occurred (InvalidParameterCombination) when calling the CreateVpnConnection operation: An ipv6 inside cidr is not allowed for VPNs using an ipv4 inside ip version

Which makes sense.

The module doesn't seem to agree with the AWS API expectations. 

### Issue Type

Bug Report

### Component Name

ec2_vpc_vpn

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.18.3]
  python version = 3.13.2 (main, Feb  4 2025, 14:51:09) [GCC 11.4.0] (/home/linuxbrew/.linuxbrew/Cellar/ansible/11.3.0_1/libexec/bin/python)
  jinja version = 3.1.6
  libyaml = True

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
amazon.aws                               9.2.0  
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /home/dandy/gitlab.cpaaseng.dev/sre-devops/ansible/.venv/lib/python3.13/site-packages
Requires: 
Required-by: 
---
Name: boto3
Version: 1.37.12
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /home/dandy/gitlab.cpaaseng.dev/sre-devops/ansible/.venv/lib/python3.13/site-packages
Requires: botocore, jmespath, s3transfer
Required-by: 
---
Name: botocore
Version: 1.37.12
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /home/dandy/gitlab.cpaaseng.dev/sre-devops/ansible/.venv/lib/python3.13/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: boto3, s3transfer
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
N/A
```

### OS / Environment

PRETTY_NAME="Ubuntu 24.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.2 LTS (Noble Numbat)"

### Steps to Reproduce

```yaml (paste below)
- name: Create a VPN connection
  amazon.aws.ec2_vpc_vpn:
    state: present
    vpn_gateway_id: "{{ vgw.vgw.id }}"
    customer_gateway_id: "{{ cgw.gateway.customer_gateway.customer_gateway_id }}"
    static_only: true
    tunnel_options:
    - PreSharedKey: "{{ peer_passphrase }}"
      TunnelInsideCidr: "x.x.x.x/x"
      TunnelInsideIpv6Cidr: ""
    - PreSharedKey: "{{ peer_passphrase }}"
      TunnelInsideCidr: "x.x.x.x/x"
      TunnelInsideIpv6Cidr: ""
    tags:
      Name: "{{ peer_name }}"
      ManagedBy: "Ansible"
```

### Expected Results

Any attempt to create the VPN with a TunnelInsideCidr results in errors.

### Actual Results

Errors described in original summary. 

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
