### ISSUE TITLE
Support for AWS RDS Multi-Tenant PDB Databases

### ISSUE THREAD

**Issue by mss** [ansible-collections/amazon.aws#2560]
### Summary

In #2275 support was added to create multi-tenant capable oracle RDS instances.

 To create the actual tenants aka PDBs one has to use the [create_tenant_database](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds/client/create_tenant_database.html) API.

The `rds_instance` doesn't support any parameter like `tenant_databases` and no separate module `rds_tenant_database` or similar exists.

### Issue Type

Feature Idea

### Component Name

rds_tenant_database, rds_instance

### Additional Information

```yaml (paste below)
- name: Create Oracle CDB
  amazon.aws.rds_instance:
    db_instance_identifier: oracle-test-1
    engine: oracle-ee-cdb
    instance_class: db.t2.small
    multi_instance: true
  register: rds_instance

- name: Create Oracle PDB
  loop: "{{ range(3) }}"
  amazon.aws.rds_tetant_database:
    db_instance_identifier: "{{ rds_instance.db_instance_identifier }}"
    tenant_db_name: "DB{{ item + 1 }}"
    master_username: admin
    master_user_password: test1234
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
