### ISSUE TITLE
Incorrect usage of variables in `route53_info` `EXAMPLES`

### ISSUE THREAD

**Issue by sivel** [ansible-collections/amazon.aws#2594]
### Summary

The `EXAMPLES` for `route53_info` show an example of:

```yaml
- name: example for using next_marker
  amazon.aws.route53_info:
    query: hosted_zone
    next_marker: "{{ first_info.NextMarker }}"
    max_items: 1
  when: "{{ 'NextMarker' in first_info }}"
```

The jinja2 delimiters should be removed such as:

```diff
-   when: "{{ 'NextMarker' in first_info }}"
+   when: "'NextMarker' in first_info"
```

### Issue Type

Documentation Report

### Component Name

route53_info

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

N/A

### Additional Information

N/A

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
