### ISSUE TITLE
Add assume_role_arn support to aws_ssm connection plugin

### ISSUE THREAD

**Issue by ethemcemozkan** [ansible-collections/amazon.aws#2633]
### Description

I’m working in a large AWS multi-account environment and implementing an Ansible-based automation solution to manage EC2 hosts across these accounts. Here’s the approach I’ve taken so far:

- Set up a central master account and defined cross-account IAM roles in each target account.
- Configured a single AWS profile using the master account credentials.
- Created dynamic inventories per account using the amazon.aws.aws_ec2 inventory plugin, leveraging the assume_role_arn feature to fetch EC2 hosts from each account.

Example configuration:
```

plugin: amazon.aws.aws_ec2
profile: master_credential_profile
regions:
  - <region>
filters:
  instance-state-name: running
assume_role_arn: arn:aws:iam::XXX:role/TargetAccountRole
hostnames:
  - instance-id
compose:
  ansible_connection: "'aws_ssm'"
  ansible_aws_ssm_bucket_name: "'<bucket>'"
  ansible_aws_ssm_region: "'<region>'"
```
### Problem

The aws_ec2 plugin correctly utilises assume_role_arn, allowing dynamic inventories to function effectively without requiring multiple profiles. However, the aws_ssm connection plugin does not support assume_role_arn. This means SSM connections fail unless I explicitly configure a separate AWS profile for each target account, which defeats the purpose of using a centralised, role-based approach.

This limitation complicates automation and increases maintenance overhead, especially in organisations with many accounts.

### Proposed Feature

Add support for assume_role_arn in the aws_ssm connection plugin, just like in the aws_ec2 inventory plugin. This would allow Ansible to:

- Use a single AWS profile (e.g., from the master account)
- Dynamically assume roles for each target account
- Seamlessly connect to EC2 instances via SSM across accounts.

### Benefits

- Simplifies Ansible and AWS configuration in multi-account setups.
- Reduces the need for manually maintained AWS profiles or external credential management.
- Makes this collection more consistent between plugins and powerful for AWS users managing resources at scale.

Let me know if you’d like me to contribute a PR for this. 

### Issue Type

Feature Idea

### Component Name

aws_ssm

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
