### ISSUE TITLE
Disable Logging of SSM Secrets to CLI

### ISSUE THREAD

**Issue by Jacob-Steele** [ansible-collections/amazon.aws#2659]
### Summary

We've recently been implementing the usage of using the lookup plugin for `ssm_parameter` through Ansible and our automation pipelines. We provide the ability to troubleshoot issues in running Ansible playbooks by turning on the verbosity mode in our pipelines. 

Using the SSM lookup plugin, there seems to be a bit of a security problem with this as the `ssm_parameter` lookup script logs the return value of the dictionary to the CLI. This appears to be happening on line https://github.com/ansible-collections/amazon.aws/blob/7eebfb660801fb7bdd224b57e358cdcd5488f458/plugins/lookup/ssm_parameter.py#L215

Even upon trying to use the modifier of `no_log: true` the SSM lookup plugin is still logging out secrets.

Here's our current usecase:

```yaml
- name: Lookup SSM Parameters
  ansible.builtin.set_fact:
    ssm_store_lookup: "{{ lookup('amazon.aws.ssm_parameter', '/path/to/store', droppath=true, bypath=true, recursive=true, region=us-east-1) }}"
  no_log: true
```
Even using the lookup in the inventory has the same issue. 

And the CLI will output with verbosity on
```
AWS_ssm path lookup term: /path/to/store in region: us-east-1
aws_ssm path lookup returned: [{'Name': 'key', 'Type': 'SecureString', 'Value': 'SOMESECRET', 'Version': 1, 'LastModifiedDate': ..., 'ARN': 'arn:aws:ssm:us-east-1:...', 'DataType': 'text'}, ...]
```

I'm wondering if it's possible to add a filter onto the `paramlist` when it's outputted to redact any of the `SecureString` type parameters in this list before the return is outputted?

### Issue Type

Feature Idea

### Component Name

ssm_parameter

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
