### ISSUE TITLE
Add support for specifying VolumeInitializationRate for EBS volumes created from snapshot

### ISSUE THREAD

**Issue by jlgoolsbee** [ansible-collections/amazon.aws#2665]
### Summary

I'd like to be able to specify the `VolumeInitializationRate` when provisioning EBS volumes created from snapshots.

Ref: https://aws.amazon.com/blogs/aws/accelerate-the-transfer-of-data-from-an-amazon-ebs-snapshot-to-a-new-ebs-volume/

### Issue Type

Feature Idea

### Component Name

ec2_vol

### Additional Information

```yaml (paste below)
- name: create volume from snapshot with volume_initialization_rate
  amazon.aws.ec2_vol:
    region: "{{ ansible_ec2_placement_region }}"
    snapshot: "{{ snapshot_id }}"
    volume_initialization_rate: 300
    volume_type: gp3
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
