### ISSUE TITLE
Add support for handling InsufficientInstanceCapacity error by allowing multiple instance types to be specified when creating an EC2 instance via the ec2_instance module

### ISSUE THREAD

**Issue by zollo** [ansible-collections/amazon.aws#2667]
### Summary

We have occasionally seen the **InsufficientInstanceCapacity** error when provisioning EC2 instances.

For example, requesting an `c6a.2xlarge` instance in `eu-west-2c` might result in the following error:

`We currently do not have sufficient c6a.2xlarge capacity in the Availability Zone you requested (eu-west-2c). Our system will be working on provisioning additional capacity. You can currently get c6a.2xlarge capacity by not specifying an Availability Zone in your request or choosing eu-west-2a, eu-west-2b`

I think we can adapt the ec2_instance module to handle this condition by allowing the user to specify multiple valid instance types. With EC2 it is possible that your application or use case could be flexible enough to have more than once acceptable instance type.

For example, I have an application that could use `c7i.xlarge`, `c6i.xlarge`, or `m7i.xlarge` instance types.

With the proposed module change, I would specify the `allowable_instance_types` param:

```yaml
- name: Provision an EC2 Instance
  amazon.aws.ec2_instance:
    name: my-app-instance
    key_name: uem-deployment-key-prd
    vpc_subnet_id: subnet-1234
    instance_type: c7i.xlarge
    allowable_instance_types:
      - m7i.xlarge
      - c6i.xlarge
    image_id: ami-123456
```

From what I can tell there is no API that would allow us to query AWS beforehand to see what instances are available based on their capacity - the only way they communicate this is through an error response on the API.

### Issue Type

Feature Idea

### Component Name

ec2_instance

### Additional Information

```yaml (paste below)
options:
  allowable_instance_types:
    description:
      - List of allowable AWS instance types.
      - If the AWS instance type specified in O(instance_type) is not avaialble in the AWS region, or there is not enough
        capacity (InsufficientInstanceCapacity), the module will retry the request using the instance types on this list.
      - The O(instance_type) will always be considered the preferred instance type.
    type: list
    elements: str
    required: false
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
