### ISSUE TITLE
How to empty S3 bucket without deleting it?

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible-collections/amazon.aws#269]
##### SUMMARY

I want to delete the contents of an S3 bucket, without deleting the bucket itself.

My use case is that I have a CloudFormation stack with buckets and other resources.
I want to delete the stack. Amazon designed the AWS::S3::Bucket resource stupidly, so that CloudFormation will fail to delete a stack if it contains a non-empty bucket. So I want to empty the bucket myself, before deleting the stack. 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
amazon.aws.aws_s3
aws_s3
amazon.aws.s3_bucket
s3_bucket

##### ANSIBLE VERSION

N/A

##### Notes

The documentation shows that I can empty *and delete* a bucket with:

```

- name: Delete a bucket and all contents
  amazon.aws.aws_s3:
    bucket: mybucket
    mode: delete
```

or

```
# Remove an S3 bucket and any keys it contains
- amazon.aws.s3_bucket:
    name: mys3bucket
    state: absent
    force: yes
```

Is there any way to tweak either of these using the existing module functionality to empty the bucket but not delete it?
