### ISSUE TITLE
ec2 filters should take non-strings as filter arguments

### ISSUE THREAD

**Issue by briantist** [ansible-collections/amazon.aws#28]
This is a resubmission of https://github.com/ansible/ansible/issues/43570 because the original issue was closed while its PR was never finished/merged.

---

The original PR needed changes and tests:
https://github.com/ansible/ansible/pull/48654

##### SUMMARY

It's unintuitive to have to quote booleans and integers with proper capitalization when used in ec2 filters (used in `ec2_ami_info`, `ec2_instance_info`, `ec2_instance`, etc.).

Non-string values should be accepted and converted as needed to what boto expects.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2.py (module_util)

##### ANSIBLE VERSION

```paste below
2.9.6
```

##### STEPS TO REPRODUCE

```yaml
- name: find
  ec2_ami_info:
    region: "{{region}}"
    filters:
      architecture: x86_64
      is-public: true
      name: "amzn-ami-2018.03.c-amazon-ecs-optimized"
      owner-id: 591542846629 # amazon's id
```

##### ACTUAL RESULTS

```paste below

```
