### ISSUE TITLE
maxresults in ec2_snapshot_info

### ISSUE THREAD

**Issue by asifiqbal** [ansible-collections/amazon.aws#312]
##### SUMMARY

Add maxresults (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSnapshots.html) to avoid filling up register. I have nearly 80k snapshots
##### ISSUE TYPE
- an attribute maxresults

##### COMPONENT NAME

ec2_snapshot_info
##### ADDITIONAL INFORMATION

I could use maxresults: 100 so the output can fit into my register: results

```yaml

---
- hosts: localhost
  gather_facts: no

  tasks:
     - amazon.aws.ec2_snapshot_info:
             filters:
                "tag:project": myproject
             maxresults: 100
       register: results
     - debug: var=results
   
```
