### ISSUE TITLE
Posibility to use variables in IAM Roles

### ISSUE THREAD

**Issue by JustDevZero** [ansible-collections/amazon.aws#314]
##### SUMMARY
We should have a way to use variables from --extra-vars or environment variables in the iam_role_arn section, such as happens with aws_security_token and others.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
plugins.inventory.aws_ec2

##### ADDITIONAL INFORMATION
Basically is needed when you manage multiple aws accounts and need to use different roles on each account.

```yaml

plugin: amazon.aws.aws_ec2
required: true
use_extra_vars: yes
iam_role_arn: arn:aws:iam::{{ACCOUNT_ID}}:role/{{ROLE_NAME}}
ansible_python_interpreter: /usr/bin/python3
regions:
  - "us-east-1"
  - "us-west-2"
filters:
  instance-state-name : running
  tag:role: manager
keyed_groups:
  - key: tags['opsworks:stack']
    prefix: opsworks_stack
  - key: tags['opsworks:layer']
    prefix: opsworks_layer
  - key: placement.region
    prefix: aws_region
compose:
  ansible_host: public_ip_address


```
Triggered with something like:

```
ACCOUNT_ID=3333333 ROLE_NAME=COOL_ROLE_NAME ansible-playbook -e IAM_ROLE=tester -i production_aws_ec2.yml -l aws_region_us_east_1 deploy_endpoints.yml

```
