### ISSUE TITLE
delete_snapshot option doesn't seem to work with ec2_ami

### ISSUE THREAD

**Issue by aardbol** [ansible-collections/amazon.aws#316]
##### SUMMARY

Setting the delete_snapshot option to yes doesn't delete the snapshots created during the AMI creation when deleting it

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_ami

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.9/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Manjaro

##### STEPS TO REPRODUCE

```yaml
    - name: Create AMI from instance
      ec2_ami:
        delete_snapshot: yes
        description: latest AMI before upgrade, created by Ansible
        instance_id: "{{ instance.instances[0].instance_id }}"
        name: "{{ instance_name + ' ' + ansible_date_time.date }}"
        no_reboot: yes
        wait: yes
      register: amidetails
```

##### EXPECTED RESULTS

AMI snapshots being deleted after manually de-registering the AMI

##### ACTUAL RESULTS

AMI snapshots will remain 

```paste below

```
