### ISSUE TITLE
rds tags not possible to configure on instance creation

### ISSUE THREAD

**Issue by aardbol** [ansible-collections/amazon.aws#317]
##### SUMMARY

On RDS instance creation, it's not possible to set the tags. It will give a type error (received dict but only accepts list)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

rds_instance

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.9/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Manjaro

##### STEPS TO REPRODUCE

```yaml
    - name: Create new RDS instance
      rds_instance:
        creation_source: snapshot
        backup_retention_period: 0
        copy_tags_to_snapshot: yes
        db_snapshot_identifier: "{{ rds_snapshot }}"
        snapshot_identifier: "{{ rds_snapshot }}"
        id: "{{ new_project_name }}"
        storage_encrypted: "{{ rdsdetails.storage_encrypted }}"
        kms_key_id: "{{ rdsdetails.kms_key_id }}"
        storage_type: "{{ rdsdetails.storage_type }}"
        engine: "{{ rdsdetails.engine }}"
        engine_version: "{{ rdsdetails.engine_version }}"
        db_subnet_group_name: "{{ rdsdetails.db_subnet_group.db_subnet_group_name }}"
        vpc_security_group_ids: "{{ rdsdetails.vpc_security_groups[0].vpc_security_group_id }}"
        zone: "{{ rdsdetails.availability_zone }}"
        wait: no
        tags:
          mytag: somevalue
```

##### EXPECTED RESULTS

Tags being set

##### ACTUAL RESULTS

Type error when setting tags when rds instance needs to be created. It is possible to modify the tags when the rds instance already exists

```paste below

```
