### ISSUE TITLE
ec2_vol issues with name and idempotency

### ISSUE THREAD

**Issue by aardbol** [ansible-collections/amazon.aws#327]
##### SUMMARY

Not setting the name option will cause the name of the volume to be "None", even if tag Name is set to something else.

Setting the name option for multiple volumes using a loop won't work because of a wrong idempotent approach here. AWS allows for multiple volumes to have the same name but this module will mark the status as ok if a volume already exists with that name

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_vol

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.9/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
```

##### STEPS TO REPRODUCE

```yaml
- name: Create new data volume(s)
  ec2_vol:
    encrypted: yes
    delete_on_termination: yes
    kms_key_id: "{{ ebs_kms_key_id }}"
    snapshot: "{{ item.snapshot_id }}"
    volume_type: gp3
    volume_size: "{{ item.volume_size }}"
    zone: "{{ instance.instances[0].placement.availability_zone }}"
    name: "{{ new_instance_name }}:/secure-data[LVM]"
  loop: "{{ data_snapshots }}"
  register: newdatavolumes
```
