### ISSUE TITLE
module fails with TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by rituparnop** [ansible-collections/amazon.aws#332]
##### SUMMARY
This issue is there for 2-3 years now I guess. There is an issue with Boto "connection.py" for SSL Proxy with string headers (suppose to be encoded). As "amazon.aws" uses boto and not boto3 (like community.aws) so its fails in env where SSL Proxy enabled.
Refer below issue links.
https://github.com/ansible-collections/community.aws/issues/313

https://github.com/boto/boto/pull/3699
https://github.com/boto/boto/pull/2718

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_vol

##### ANSIBLE VERSION

```
ansible 2.10.8
  config file = None
  configured module search path = ['/home/ansible_runner_users/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/venv/lib/python3.7/site-packages/ansible
  executable location = /opt/venv/bin/ansible
  python version = 3.7.7 (default, Apr 30 2020, 09:28:25) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### CONFIGURATION

```paste below
DEFAULT_GATHERING(env: ANSIBLE_GATHERING) = explicit
```

##### OS / ENVIRONMENT

RedHat UBI image for Docker "Linux 83b33a6a8c4c 4.18.0-240.15.1.el8_3.x86_64" running ansible 2.10

##### STEPS TO REPRODUCE

```
---
- name: use manage disk role playbook
  hosts: localhost
  vars:
    proxy_env:
      http_proxy: "{{ lookup('env', 'HTTP_PROXY') | default('', True) }}"
      https_proxy: "{{ lookup('env', 'HTTPS_PROXY') | default('', True) }}"
  gather_facts: no
  tasks:
      - name: Add disk to vm
        amazon.aws.ec2_vol:
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          instance: "{{ instance_id }}"
          region: "{{ region }}"
          device_name: "{{ device_name }}"
          volume_size: "{{ volume_size }}"
          delete_on_termination: "{{ delete_on_termination }}"
        environment: "{{ proxy_env }}"
```

##### EXPECTED RESULTS
Volume attached

##### ACTUAL RESULTS

Module failing to connect via proxy with below message.

```paste below
connection.py", line 796, in proxy_ssl, sock.sendall("CONNECT %s HTTP/1.0\r\n" % host), TypeError: a bytes-like object is required, not 'str',
```
