### ISSUE TITLE
amazon.aws.ec2_vol "Volume None does not exist" when volume exists and is attached to instance

### ISSUE THREAD

**Issue by ieugen** [ansible-collections/amazon.aws#336]
##### SUMMARY

I think that there is an issue when attaching the volume to an instance.
The volume is not found by tag. It exists and is attached to instance.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_vol

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /REDACTED/ansible/ansible.cfg
  configured module search path = ['/REDACTED/ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

##### CONFIGURATION

```paste below

ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
COLLECTIONS_PATHS(/REDACTED/ansible/ansible.cfg) = ['/REDACTED/ansible/collections']
COMMAND_WARNINGS(/REDACTED/ansible/ansible.cfg) = False
DEFAULT_ASK_VAULT_PASS(/REDACTED/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = ['/REDACTED/ansible/inventory']
DEFAULT_ROLES_PATH(/REDACTED/ansible/ansible.cfg) = ['/REDACTED/ansible/roles']
HOST_KEY_CHECKING(/REDACTED/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/REDACTED/ansible/ansible.cfg) = /usr/bin/python3

```

requirements.yml
```
collections:
  - name: community.docker
    version: 1.3.0
  - name: amazon.aws
    version: 1.4.0
  - name: community.aws
    version: 1.4.0
```
requirements.txt
```
boto3>=1.17.12 # Used by collections.community.aws
botocore>=1.12.249
jsondiff>=1.2.0  # Used by community-docker-docker-stack-module
pyyaml>=5.4.1  # Used by community-docker-docker-stack-module
```

##### OS / ENVIRONMENT

```
Linux daos-495 5.10.0-5-amd64 #1 SMP Debian 5.10.26-1 (2021-03-27) x86_64 GNU/Linux
```
##### STEPS TO REPRODUCE

I have the following 

```yaml
- hosts: dev2
  tasks:
    - amazon.aws.ec2_metadata_facts:
    - amazon.aws.ec2_vol:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        instance: "{{ hostvars['dev2']['instance_id']}}"
        name: dev_vol
        modify_volume: no
        region: us-west-1
        volume_size: 150
        volume_type: gp3
        throughput: 125
        iops: 6000
      register: dev_volume
      delegate_to: localhost
```

##### EXPECTED RESULTS

The volume exists and is attached to the instance, I would like to receive confirmation that that is the case

##### ACTUAL RESULTS

```paste below

ansible-playbook -v aws-volume.yml -v

TASK [amazon.aws.ec2_vol] ***********************************************************************************************************************************************************************
task path: /REDACTED/ansible/tasks/aws-rel-triple-store-volumes.yml:10
[WARNING]: Filters1 dev_vol
ok: [dev2] => {"changed": false, "msg": "Volume None does not exist"}
```

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/ec2_vol.py`](https://github.com/['ansible-collections/amazon.aws', 'ansible-collections/community.aws', 'ansible-collections/community.vmware']/blob/main/plugins/modules/ec2_vol.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @jillr @lwade @s-hertel @tremble @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ieugen** [comment]
The step that fails is: 

ec2_vol.py
````
    elif name:
        find_params['Filters'] = ansible_dict_to_boto3_filter_list({'tag:Name': name})
````

**Comment by markuman** [comment]
I cannot reproduce it.

```yml
    - name: make sure volume exists
      amazon.aws.ec2_vol:
        volume_type:  gp3
        volume_size:  100
        state: present
        name: madewithansible
        zone: eu-central-1c

    - name: attache volume
      amazon.aws.ec2_vol:
        instance: i-07e6cc6dec28b08db
        name: madewithansible
        modify_volume: no
        region: eu-central-1
        device_name: xvda
      register: dev_volume

    - debug: msg="{{ dev_volume }}"
```

Results in 

```
AWS_PROFILE=myaws ap test.yml     
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ****************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [ec2 instance] *************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [attache volume] ***********************************************************************************************************************************************************************************************
changed: [localhost]

TASK [debug] ********************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": true,
        "device": "xvda",
        "failed": false,
        "volume": {
            "attachment_set": {
                "attach_time": "2021-04-27T18:57:26+00:00",
                "deleteOnTermination": false,
                "device": "xvda",
                "instance_id": "i-07e6cc6dec28b08db",
                "status": "attaching"
            },
            "create_time": "2021-04-27T18:52:42.691000+00:00",
            "encrypted": false,
            "id": "vol-00115095d0819c080",
            "iops": 4000,
            "size": 100,
            "snapshot_id": "",
            "status": "in-use",
            "tags": {
                "Name": "madewithansible"
            },
            "throughput": null,
            "type": "io1",
            "zone": "eu-central-1c"
        },
        "volume_id": "vol-00115095d0819c080",
        "volume_type": "io1"
    }
}

PLAY RECAP **********************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
