### ISSUE TITLE
aws_secret getting IncompleteSignatureException when using AWS credentials: 'assumed_role.sts_creds.access_key' not a valid key=value pair (missing equal-sign)

### ISSUE THREAD

**Issue by Trozz** [ansible-collections/amazon.aws#348]
##### SUMMARY
Issue using aws.aws_secret with access, secret and session keys.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_secret

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.0b4]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
```

##### CONFIGURATION
No Changes

##### OS / ENVIRONMENT

Runner = CentOS 8 container (AWX)

##### STEPS TO REPRODUCE

Attempt to set a variable from a lookup using access key, secret key and security token

```yaml
- name: Assume role
  delegate_to: localhost
  community.aws.sts_assume_role:
    role_arn: "arn:aws:iam::XXXX:role/YYYY"
    role_session_name: "Ansible"
  register: assumed_role


- name: Set Variables
  delegate_to: localhost
  set_fact:
    secret: "{{ lookup('amazon.aws.aws_secret', 'Secret-Name', region='eu-west-1', aws_access_key='{{ assumed_role.sts_creds.access_key }}', aws_secret_key='{{ assumed_role.sts_creds.secret_key }}', aws_security_token='{{ assumed_role.sts_creds.session_token }}' ) }}"

```

##### EXPECTED RESULTS

Secret placed in variable

##### ACTUAL RESULTS

Error is returned resulting from IncompleteSignatureException

```paste below
fatal: [XXXX]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'amazon.aws.aws_secret'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed to retrieve secret: An error occurred (IncompleteSignatureException) when calling the GetSecretValue operation: 'assumed_role.sts_creds.access_key' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential={{ assumed_role.sts_creds.access_key }}/20210429/eu-west-1/secretsmanager/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=8f6a9c5f1a5c5289585ae5a31caae21d1a8186dfd632b4c688bd8ca74c590db9'."
}
```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/lookup/aws_secret.py`](https://github.com/['ansible-collections/amazon.aws', 'ansible-collections/community.aws', 'ansible-collections/community.vmware']/blob/main/plugins/lookup/aws_secret.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by abikouo** [comment]
@Trozz thanks for taking time to report this issue.
The ``aws_secret`` lookup plugin was not reading template var, this has been fixed on the following PR #351
Could you please try it ?

**Comment by abikouo** [comment]
@Trozz when using a lookup plugin you are already in a jinja context, so you should remove variable start and end character.
could you please try using the following syntax ? 

```
- name: Set Variables
  delegate_to: localhost
  set_fact:
    secret: "{{ lookup('amazon.aws.aws_secret', 'Secret-Name', region='eu-west-1', aws_access_key=assumed_role.sts_creds.access_key, aws_secret_key=assumed_role.sts_creds.secret_key, aws_security_token=assumed_role.sts_creds.session_token ) }}"
```
