### ISSUE TITLE
Ability to use path style for S3

### ISSUE THREAD

**Issue by KoltesDigital** [ansible-collections/amazon.aws#363]
##### SUMMARY

Add attribute in S3 tasks: boolean `path_style`, defaults to `no`.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

Some providers still use path-style endpoints. While the endpoint may be overridden with `s3_url` (and `rgw: yes`), I believe the (mandatory) bucket name is still appended, and it should not.

```yaml
    - name: Simple PUT operation
      amazon.aws.aws_s3:
        bucket: unused
        mode: put
        object: /file.ext
        path_style: yes
        rgw: yes
        s3_url: https://bucket-name.region.example.com
        src: /path/to/file.ext
```

As shown above, when `path_style: yes` and `rgw: yes`, the bucket name is not used anymore and should not be required.

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
@KoltesDigital: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE/bug_report.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jillr** [comment]
Hi @KoltesDigital, We're a little confused by your example and would like to clarify.  In the example task it sounds like you have a bucket named `bucket-name` (maybe I'm misunderstanding the example name here) and you want to provide a virtual-host style endpoint that includes that bucket name, and then also append a path-style bucket name of `unused` to the url?  So ending up with something like, `https://bucket-name.region.example.com/unused`.

Using the module today, a task like this:
```
 amazon.aws.aws_s3:
    bucket: mybucket
    object: /my/desired/key.txt
    src: /usr/local/myfile.txt
    mode: put
    rgw: true
    s3_url: "http://localhost:8000"
```
should create a path-style URL like: `http://localhost:8000/mybucket`

What behaviour would you expect with `path_style: true` vs `path_style: false`?
