### ISSUE TITLE
ec2_vol doesnt not support vol_type:gp3 *document says it does*

### ISSUE THREAD

**Issue by bendaniels052** [ansible-collections/amazon.aws#384]
##### SUMMARY
When trying to create a new volume with the type set to `gp3`, the volume is defaulted to `io1` which isn't defined anywhere in the vars. Looking at the ansible documentation, `gp3` is defined as supported and a choice which we're aloud to choose from. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`amazon.aws.ec2_vol`

Documentation to show `gp3` is supported 
https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_vol_module.html#parameter-volume_type

##### ANSIBLE VERSION
```
ansible 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/local/CD2/-sysop-dabhiy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/local/CD2/-sysop-dabhiy/.venv-ansible/lib64/python3.6/site-packages/ansible
  executable location = /home/local/CD2/-sysop-dabhiy/.venv-ansible/bin/ansible
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

```yaml

    - name: Add volume to ec2
      amazon.aws.ec2_vol:
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        security_token: '{{ aws_session_token }}'
        profile: '{{ aws_profile }}'
        volume_size: "{{ vol_size | default('100') }}"
        volume_type: gp3
        iops: "{{ vol_iops | default('3000') }}"
        encrypted: yes
        kms_key_id: '*************'
        device_name: '/dev/xvdbc'
        zone: "{{ vol_zone | default('eu-west-1c') }}"
```

Unable to find the files related to this module. 

##### EXPECTED RESULTS
Module parameters - volume should be deployed with `volume_type: gp3` 

```
changed: [localhost] => {
    "changed": true,
    "device": null,
    "invocation": {
        "module_args": {
            "aws_access_key": "******************",
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "debug_botocore_endpoint_logs": false,
            "delete_on_termination": false,
            "device_name": "/dev/xvdbc",
            "ec2_url": null,
            "encrypted": true,
            "id": null,
            "instance": null,
            "iops": 3000,
            "kms_key_id": "**********************",
            "modify_volume": false,
            "name": null,
            "profile": "WE1-P2-0870-role_ENGINEERING",
            "purge_tags": false,
            "region": "eu-west-1",
            "security_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "snapshot": null,
            "state": "present",
            "tags": {},
            "throughput": null,
            "validate_certs": true,
            "volume_size": 100,
            "volume_type": "gp3",
            "zone": "eu-west-1c"
        }
    },
``` 

##### ACTUAL RESULTS
Actual debug output -- NOTE volume is be deployed with `volume_type: io1` 

```
    "volume": {
        "attachment_set": {
            "attach_time": null,
            "deleteOnTermination": null,
            "device": null,
            "instance_id": null,
            "status": null
        },
        "create_time": "2021-06-11T12:37:14.534000+00:00",
        "encrypted": true,
        "id": "vol-0df8571f6d2a67de5",
        "iops": 3000,
        "size": 100,
        "snapshot_id": "",
        "status": "available",
        "tags": {
            "cloud-environment": "WE1-P2-0870",
            "cpm backup": "WE1_P2_Nobackups"
        },
        "throughput": null,
        "type": "io1",
        "zone": "eu-west-1c"
    },
    "volume_id": "vol-0df8571f6d2a67de5",
    "volume_type": "io1"
}
```
