### ISSUE TITLE
Support `throughtput` parameter for GP3 volume types as part of ec2.volumes 

### ISSUE THREAD

**Issue by gtie** [ansible-collections/amazon.aws#395]
##### SUMMARY
Support `throughtput` parameter for GP3 volume types as part of the ec2.volumes parameter

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ec2.py

##### ADDITIONAL INFORMATION

While GP3 EBS volumes can be created together with an EC2 instance using the `ec2` module,  the feature of setting a custom `throughput` parameter is still missing. This leads to very ugly workarounds.

Ideally, we should be able to specify it directly as in:
```
- amazon.aws.ec2:
    key_name: mykey
    group: webserver
    instance_type: c3.medium
    image: ami-123456
    wait: yes
    wait_timeout: 500
    volumes:
      - device_name: /dev/xvda
        volume_type: gp3
        volume_size: 8
        throughput: 250
```

This type of definition is already supported by the `ec2_vol` module, but it's not yet present in `ec2`
