### ISSUE TITLE
Ability to toggle off leading_separator for keyed_groups

### ISSUE THREAD

**Issue by hs-amartin** [ansible-collections/amazon.aws#402]
### Summary

I am in the middle of migrating from a manually managed inventory file to a generated one, and the fact that I can't omit the `_` even if I don't specify a prefix means I cannot exactly replicate my existing group structure. Also leading underscores are kind of weird.

### Issue Type

Feature Idea

### Component Name

keyed_groups

### Additional Information

```yaml (paste below)
plugin: aws_ec2
boto_profile: account7-profile
regions:
  - us-east-1
keyed_groups:
  - key: tags['Name']|regex_replace("-account7-.*","")
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
