### ISSUE TITLE
amazon.aws.ec2_group idempotency issue.

### ISSUE THREAD

**Issue by csamarajeewa** [ansible-collections/amazon.aws#459]
### Summary

Idempotency issue with amazon.aws.ec2_group ansible module, I changed few ingress rules to an existing security group. This resulted in a new security group with the same name being created instead of updating the existing one. 

### Issue Type

Bug Report

### Component Name

amazon.aws.ec2_group

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.4
 config file = None
  configured module search path = ['/redact', '/redact']
  ansible python module location = /redact = /redact
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list

Collection             Version
---------------------- -------
amazon.aws             1.3.0  
ansible.netcommon      1.5.0  
community.aws          1.3.0  
community.azure        1.0.0  
community.crypto       1.1.1  
community.digitalocean 1.0.0  
community.general      1.1.0  
community.grafana      1.0.0  
community.kubernetes   1.0.0  
community.libvirt      1.0.0  
community.mongodb      1.0.0  
community.mysql        1.0.0  
community.network      1.1.0  
community.postgresql   1.1.0  
community.proxysql     1.0.0  
community.rabbitmq     1.0.1  
community.skydive      1.0.0  
community.vmware       1.2.0  
community.windows      1.0.0  
community.zabbix       1.0.0  

```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore

Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /redact/ansible-venv/ansible10/lib/python3.8/site-packages
Requires: 
Required-by: 
---
Name: boto3
Version: 1.16.63
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /redact/ansible-venv/ansible10/lib/python3.8/site-packages
Requires: jmespath, botocore, s3transfer
Required-by: 
---
Name: botocore
Version: 1.19.63
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /redact/ansible-venv/ansible10/lib/python3.8/site-packages
Requires: python-dateutil, urllib3, jmespath
Required-by: s3transfer, boto3

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

n/a
```

### OS / Environment

awx docker.

### Steps to Reproduce

```yaml (paste below)

Can only describe, not paste.
-- existing var for security group.
     -- updated ingress rules.
     -- ** did not change name

```

### Expected Results

Security group name did not change. Only new ingress rules added and tags modified. I expected the existing security group to get updated, but instead the module created a new security group with the same name. ``

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by goneri** [comment]
Hi @csamarajeewa,

Thank you for reporting this. The 1.5.0 release may fix this, can you please upgrade and check if the problem remains?

**Comment by jatorcasso** [comment]
Hi @csamarajeewa,

I can't reproduce your findings with 1.3.0 of the collection running the following tests. If you can provide more information on how to reproduce the issue, please re-open this issue with those details.

```
    - name: Add a rule that auto creates another security group
      ec2_group:
        name: "{{ ec2_group_name }}"
        description: "{{ ec2_group_description }}"
        state: present
        purge_rules: no
        rules:
        - proto: 'tcp'
          group_name: "{{ resource_prefix }} - Another security group"
          group_desc: Another security group
          ports: 7171
      register: result

    - ec2_group_info:
        filters:
          group-name: "{{ ec2_group_name }}"
      register: sg

    - name: check security group
      assert:
        that:
          - result.changed
          - sg.security_groups | length == 1
          - "{{ 7171 in sg.security_groups[0].ip_permissions | map(attribute='from_port') }}"

    - name: Modify rule with different port
      ec2_group:
        name: "{{ ec2_group_name }}"
        description: "{{ ec2_group_description }}"
        state: present
        rules:
        - proto: 'tcp'
          group_name: "{{ resource_prefix }} - Another security group"
          ports: 7172
      register: result

    - ec2_group_info:
        filters:
          group-name: "{{ ec2_group_name }}"
      register: sg_updated

    - name: check that existing group was modified and no new one was created
      assert:
        that:
          - sg_updated.security_groups | length == 1
          - "{{ 7171 not in sg_updated.security_groups[0].ip_permissions | map(attribute='from_port') }}"
          - "{{ 7172 in sg_updated.security_groups[0].ip_permissions | map(attribute='from_port') }}"
          - sg_updated.security_groups[0].group_id == sg.security_groups[0].group_id
```
