### ISSUE TITLE
ec2_instance keeps default value even if set in launch template 

### ISSUE THREAD

**Issue by emanuele-leopardi** [ansible-collections/amazon.aws#462]
##### SUMMARY
It looks like there are still some default values that are not taken into account by this module even if passing a launch template

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_instance
##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = /Users/ema/Documents/bin/kl_infrastructure/ansible/bda-appquality/ansible.cfg
  configured module search path = ['/Users/ema/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.0 (default, Oct 27 2020, 14:15:17) [Clang 12.0.0 (clang-1200.0.32.21)]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS() = -o ConnectionAttempts=10 -o ControlMaster=auto -o ControlPersist=10m -o StrictHostKeyCh
ANSIBLE_SSH_RETRIES() = 5
DEFAULT_FORCE_HANDLERS() = True
DEFAULT_STRATEGY() = linear
DEFAULT_TIMEOUT() = 120
HOST_KEY_CHECKING() = False
RETRY_FILES_ENABLED() = False
```

##### OS / ENVIRONMENT

MacOS 11.2.3 
##### STEPS TO REPRODUCE

First of all let's define some variables
```yaml
instance:
    name: kl-{{ proj_name }}-backend
    subnet: kl-{{ proj_name }}-db-a
    ami_id: ami-fooobarrrbaaaz
    instance_type: t3.micro
    state: present
    termination_protection: false
    region: "eu-south-1" #Milan
    security_groups:
      - kl-{{ proj_name }}-backend-sg
    network:
      assign_public_ip: true
      delete_on_termination: true
      description: kl-{{ proj_name }}-backend
    env: lab
```
then we use this to create a nice ec2_launch_template

```yaml
- name: Create | Update Launch Template
  ec2_launch_template:
    state: "{{ instance.state | default('present')}}"
    template_name: "{{ instance.name | default(omit) }}-launch-template"
    image_id: "{{ instance.ami_id }}"
    instance_type: "{{ instance.instance_type }}"
    key_name: "{{ instance.key | default('ssh_key') }}"
    region: "{{ instance.region }}"
    tags:
      Name: "{{ instance.name }}-launch-template"
```
we register the Id and then we use it to call ec2_instance
```yaml

- name: create instance from launch_template
  ec2_instance:
    launch_template: 
      id: "{{ launch_template_id }}"
      region: "{{ instance.region }}"
```

##### EXPECTED RESULTS

The expected result is that the instance gets create with instance.instance_type == t3.micro 

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/rt/949k8fvs20bbvn_dv1drjv9h0000gn/T/ansible_ec2_instance_payload_li974i3k/ansible_ec2_instance_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_instance.py", line 1622, in ensure_present
  File "/var/folders/rt/949k8fvs20bbvn_dv1drjv9h0000gn/T/ansible_ec2_instance_payload_li974i3k/ansible_ec2_instance_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_instance.py", line 1655, in run_instances
  File "/var/folders/rt/949k8fvs20bbvn_dv1drjv9h0000gn/T/ansible_ec2_instance_payload_li974i3k/ansible_ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/core.py", line 289, in deciding_wrapper
    return unwrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Unsupported) when calling the RunInstances operation: The requested configuration is currently not supported. Please check the documentation for supported configurations.
fatal: [localhost]: FAILED! => {
    "boto3_version": "1.17.54",
    "botocore_version": "1.20.54",

.
.
.
.
"image": null,
"image_id": null, <-- correctly unset value (I guess taken from the launch template)
"instance_ids": [],
"instance_initiated_shutdown_behavior": null,
"instance_role": null,
"instance_type": "t2.micro",   <------ default value set here that seems to override the launch template
"key_name": null,
"launch_template": {
     "id": "lt-xxxxxxxxxxxx"
 },
"name": null,
"network": null,
```
