### ISSUE TITLE
ec2_instance fails if there is no default vpc and no vpc_subnet_id specified

### ISSUE THREAD

**Issue by nerijus** [ansible-collections/amazon.aws#467]
##### SUMMARY

There is only one VPC in the region, but it is not default (Default VPC: No). I.e. there is no default VPC at all in this region.
I try to create ec2 instance by using:
```
- name: Create a new ec2 instance
  ec2_instance:
    name: "{{ route53_hostname }}"
    key_name: "{{ key_name }}"
    security_group: unhindered
    instance_type: "{{ size }}"
    image_id: 'ami-0d2f2...'
    region: "{{ region }}"
    availability_zone : "{{ availability_zone }}"
    volumes: "{{ volumes }}"
```
It fails with:
```
 File "/tmp/ansible_ec2_instance_payload_c9xfa938/ansible_ec2_instance_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_instance.py", line 1409, in get_default_subnet
TypeError: 'NoneType' object is not subscriptable

```
The docs at `https://docs.ansible.com/ansible/latest/collections/community/aws/ec2_instance_module.html#parameter-availability_zone` say that availability zone is useful if not specifying the vpc_subnet_id parameter.
But it does not work in my case. When I specify `vpc_subnet_id`, it works.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

  ec2_instance
##### ANSIBLE VERSION

```paste below
ansible 2.10.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nerijus/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

**Comment by ansibullbot** [comment]
cc @ryansb
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nerijus** [comment]
We have got emails from aws that EC2 Classic will be deprecated, and it said that we don't have classic resources in our regions.

**Comment by tremble** [comment]
The order of VPCs when calling describe_vpcs is not guaranteed.  Picking what happens to be returned as the first is going to be non-deterministic in accounts with multiple VPCs.

If there's no default VPC and no subnet specified I think it's perfectly reasonable for the module to fail.

**Comment by nerijus** [comment]
But I am talking about situation when "There is only one VPC in the region, but it is not default". So I assume it is safe to return first when there is only one VPC? And yes, if there are multiple VPCs, then it should fail as before.

**Comment by tremble** [comment]
Take the simple example that you add a new VPC to your account, suddenly all playbooks relying on that VPC being the only VPC fail.  While what you're suggesting would work for your current, specific, use-case (a single VPC, with no VPC marked as default), however, in my opinion it's not a "good" solution because it adds fragile extra logic while only solving for a very specific edge-case.

Managing Security Groups and Instances is already very complex code (due to the massive array of options), adding special cases to try to **guess** what people want simply makes things unpredictable. 

The specific case of falling back to the "default subnet" for a specified AZ in the "default VPC" is different because Amazon explicitly ensures it is the only VPC marked as "default" in the region and the only subnet marked as "default" in that availability zone.  This in turn means that adding additional VPCs or additional subnets has no unexpected side effects.  Additionally, while the AWS Web UI might automatically pick a VPC/subnet for you automatically, it's showing you what it's picked and there's then an explicit confirmation step before you launch the resource.

There are already modules which support fetching the information you would need (ec2_vpc_subnet_info), I'd strongly recommend using those so you can be more explicit about the rules you want to follow for picking the subnets.

**Comment by azrdev** [comment]
> If there's no default VPC and no subnet specified I think it's perfectly reasonable for the module to fail.

but it should emit a better error message than a backtrace and `TypeError: 'NoneType' object is not subscriptable`

**Comment by shadycuz** [comment]
There is definitely a bug in the code. Take this example:

```
- name: Terminate the firewalls
  amazon.aws.ec2_instance:
    instance_ids: "{{ decommission_instances | map(attribute='instance_id') | list }}"
    state: terminated
    wait: true
```

Results in:

> TASK [decommission : Terminate the firewalls] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No default subnet could be found - you must include a VPC subnet ID (vpc_subnet_id parameter)."}

I'm pretty sure I can terminate ec2 instances by id using the AWS API, without specifying a subnet_id.
