### ISSUE TITLE
IPv6 support in ec2_vpc_route_table

### ISSUE THREAD

**Issue by boutetnico** [ansible-collections/amazon.aws#477]
##### SUMMARY
Allow usage of IPv6 CIDR in `ec2_vpc_route_table`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ec2_vpc_route_table.py

##### ADDITIONAL INFORMATION

An old PR tried to fix it already: https://github.com/ansible/ansible/pull/50220.
This would solve the error that occurs when we use an IPv6 CIDR.

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateRoute operation: Value (::/0) for parameter destinationCidrBlock is invalid. This is not a valid CIDR block.
fatal: [localhost]: FAILED! => {"boto3_version": "1.17.3", "botocore_version": "1.20.3", "changed": false, "error": {"code": "InvalidParameterValue", "message": "Value (::/0) for parameter destinationCidrBlock is invalid. This is not a valid CIDR block."}, "msg": "Couldn't create route: An error occurred (InvalidParameterValue) when calling the CreateRoute operation: Value (::/0) for parameter destinationCidrBlock is invalid. This is not a valid CIDR block.", "response_metadata": {"http_headers": {"cache-control": "no-cache, no-store", "connection": "close", "date": "Wed, 10 Feb 2021 08:07:32 GMT", "server": "AmazonEC2", "strict-transport-security": "max-age=31536000; includeSubDomains", "transfer-encoding": "chunked", "x-amzn-requestid": "42c90a54-5eb3-42fd-a993-6c73cfccbe0f"}, "http_status_code": 400, "request_id": "42c90a54-5eb3-42fd-a993-6c73cfccbe0f", "retry_attempts": 0}}
```

```yaml
  ec2_vpc_route_table:
      routes:
        - dest: 0.0.0.0/0
          gateway_id: gw-id
        - dest: ::/0
          gateway_id: gw-id
      subnets:
        - subnet-1
        - subnet-2
        - subnet-3
      vpc_id: vpc-id
```
