### ISSUE TITLE
amazon.aws.aws_s3 incorrect loop handling and failure message

### ISSUE THREAD

**Issue by agnesdober-db** [ansible-collections/amazon.aws#504]
### Summary

In order to download multiple files from an s3 bucket, I wanted to loop through the task, putting the values for object and dest into variables. This returned the error message: FAILED! => {"msg": "'bucket' is undefined"}, even though the bucket was static and defined. 

Running the task without the loop with one of the files given statically as a test resulted in a successful execution.

(The localhost is an AWS Instance with the appropriate role attached.)

### Issue Type

Bug Report

### Component Name

aws_s3

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/rundeck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
Collection            Version
--------------------- -------
amazon.aws            1.5.0
ansible.posix         1.3.0
ansible.windows       1.7.2
chocolatey.chocolatey 1.1.0
community.aws         1.5.0
community.crypto      1.8.0
community.general     3.5.0
community.mysql       2.1.1
community.postgresql  1.4.0
community.windows     1.6.0
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /usr/lib/python3/dist-packages
Requires:
Required-by:
---
Name: boto3
Version: 1.9.253
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /usr/lib/python3/dist-packages
Requires:
Required-by:
---
Name: botocore
Version: 1.16.19
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /usr/lib/python3/dist-packages
Requires:
Required-by:
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1047-aws x86_64)

### Steps to Reproduce

```yaml (paste below)
# main.yml from role/tasks
---
# This task is successful
- name: Download file test
  amazon.aws.aws_s3:
    bucket: my-bucket
    object: "folder1/folder1/file.rar"
    dest: /tmp/file.rar
    mode: get
    region: eu-central-1
  delegate_to: localhost

# This task fails
- name: Download files
  amazon.aws.aws_s3:
    bucket: my-bucket
    object: "{{ item.name }}"
    dest: "{{ item.location }}"
    mode: get
    region: eu-central-1
  loop: "{{ bucket-files }}"
  delegate_to: localhost


# main.yml from role/vars
---
bucket-files:
  - name: "folder1/folder1/file.exe"
    location: /tmp/file.exe

  - name: "folder1/folder1/file.rar"
    location: /tmp/file.rar
```

### Expected Results

Both tasks are successful, ansible is able to loop through.

### Actual Results

```console (paste below)
fatal: [machinename]: FAILED! => {"msg": "'bucket' is undefined"}
```
(No matter the amount of v-s, this was all I got.)

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
