### ISSUE TITLE
ec2_instance updates exisitng instances instead of creating new

### ISSUE THREAD

**Issue by poleszcz** [ansible-collections/amazon.aws#526]
### Summary

I'm using amazon.aws 2.0. I want to create new instance with module ec2_instance but instead ansible is updating other instances that use the same image. Apparently I'm missing something. Based on documentation I don't see how module is deciding to update or create new instance.

Collection       Version
---------------- -------
amazon.aws       2.0.0 

```
- name: Create EC2 instance
  amazon.aws.ec2_instance:
    key_name: "{{ aws_ssh_key_name }}-{{ env_timestamp }}"
    region: "{{ region }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami }}"
    wait: yes
    wait_timeout: 600
    tags:
      Name: "{{ ec2_instance_name }}-{{ env_timestamp }}"
      Creator: "{{ creator }}"
      project: "{{ project }}"
    vpc_subnet_id: "{{ subnet_id }}"
    network:
      assign_public_ip: yes
      groups:
        - "{{ security_group.group_name }}"
  register: ec2
```

### Issue Type

Bug Report

### Component Name

ec2_instance

### Ansible Version

```
ansible [core 2.11.3] 
  config file = None
  configured module search path = ['/Users/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/XXX/Library/Python/3.8/lib/python/site-packages/ansible
  ansible collection location = /Users/XXX/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/XXX/Library/Python/3.8/bin/ansible
  python version = 3.8.2 (default, Apr  8 2021, 23:19:18) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = False
```

### Collection Versions

```
Collection       Version
---------------- -------
amazon.aws       2.0.0  
community.docker 1.9.1  
```

### AWS SDK versions

```
WARNING: Package(s) not found: boto
Name: boto3
Version: 1.17.112
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /Users/XXX/Library/Python/3.8/lib/python/site-packages
Requires: jmespath, botocore, s3transfer
Required-by: 
---
Name: botocore
Version: 1.20.112
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /Users/XXX/Library/Python/3.8/lib/python/site-packages
Requires: jmespath, urllib3, python-dateutil
Required-by: s3transfer, boto3
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

local: MacOS

### Steps to Reproduce

I have few preexisting instances and they are getting updated and new instance is not created.

### Expected Results

I exepect to get new instance created.

### Actual Results

ec2_instance returns list of 6 updated instances

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
