### ISSUE TITLE
ec2_instance module doesn't have count

### ISSUE THREAD

**Issue by rh-dluong** [ansible-collections/amazon.aws#536]
### Summary

ec2_instance module doesn't have count parameter like ec2 module does

### Issue Type

Bug Report

### Component Name

ec2_instance

### Ansible Version

```console (paste below)
$ ansible --version
2.11
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
amazon.aws
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
- name: Create ec2 instance(s) for controller hybrid node(s)
  amazon.aws.ec2_instance:
    key_name: "{{ key_name }}"
    instance_type: t2.large
    wait: yes
    count: "{{ count | default('1') }}"
    region: "{{ region }}"
    network:
      assign_public_ip: yes
      group: lab-sg
    vpc_subnet_id: "{{ subnet }}"
    image_id: "{{ ami }}"
    tags:
        Name: "{{ vm_name }} controller hybrid"
        lab_managed: lab_managed
```

### Expected Results

It provisions correctly

### Actual Results

```console (paste below)
Unsupported parameters for (amazon.aws.ec2_instance) module: count
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
