### ISSUE TITLE
ec2_key: include KeyPairId in result

### ISSUE THREAD

**Issue by andytson** [ansible-collections/amazon.aws#546]
### Summary

I want to limit the ec2:RunInstances to specific EC2 keys which are created by ansible, but only the fingerprint and name are returned as a result of ec2_key.

DescribeKeyPairs and ImportKeyPair return a KeyPairId, which is what's required for generating the ARN of the IAM policy

Please can the KeyPairId be included in the e2c_key result?

### Issue Type

Feature Idea

### Component Name

ec2_key

### Additional Information

```yaml (paste below)
- amazon.aws.ec2_key:
    name: myapp
    key_material: ".."
  register: aws_ec2_key

- community.aws.iam_policy:
    iam_type: user
    iam_name: myapp
    policy_name: ec2
    policy_json:
      Version: "2012-10-17"
      Statement:
        - Effect: allow
          Action: ec2:RunInstances
          Resource:
            - "arn:aws:ec2:us-east-1:1234567:instance/*"
            - "arn:aws:ec2:us-east-1:1234567:key-pair/{{ aws_ec2_key.key.id }}"
            - "arn:aws:ec2:us-east-1:1234567:security-group/*"
            - "arn:aws:ec2:us-east-1:1234567:volume/*"
            - "arn:aws:ec2:us-east-1:1234567:network-interface/*"
            - "arn:aws:ec2:us-east-1:1234567:subnet/*"
            - "arn:aws:ec2:us-east-1::image/*"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
