### ISSUE TITLE
ec2_key: provide the ability to assign tags

### ISSUE THREAD

**Issue by andytson** [ansible-collections/amazon.aws#547]
### Summary

I want to use tags on ec2_keys for various purposes, such as limiting IAM policies, for example limiting ec2:RunInstances to only support keypairs with a set tag.

Tags are supported on KeyPairs

Please can the ability to create/delete tags be added to ec2_keys as is done on other modules?

### Issue Type

Feature Idea

### Component Name

ec2_key

### Additional Information

```yaml (paste below)
- amazon.aws.ec2_key:
    name: myapp
    key_material: ".."
    tags:
      "example.com/myapp": "true"

- community.aws.iam_policy:
    iam_type: user
    iam_name: myapp
    policy_name: ec2
    policy_json:
      Version: "2012-10-17"
      Statement:
        - Effect: allow
          Action: ec2:RunInstances
          Resource: "arn:aws:ec2:us-east-1:1234567:key-pair/*"
          Condition:
            StringEquals:
              "aws:ResourceTag/example.com/myapp": "true"
        - Effect: allow
          Action: ec2:RunInstances
          Resource:
            - "arn:aws:ec2:us-east-1:1234567:instance/*"
            - "arn:aws:ec2:us-east-1:1234567:security-group/*"
            - "arn:aws:ec2:us-east-1:1234567:volume/*"
            - "arn:aws:ec2:us-east-1:1234567:network-interface/*"
            - "arn:aws:ec2:us-east-1:1234567:subnet/*"
            - "arn:aws:ec2:us-east-1::image/*"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
