### ISSUE TITLE
Add example for Searching volumes based on EC2 Instance ID - "state: list" functionality from ec2_vol

### ISSUE THREAD

**Issue by jrglynn2** [ansible-collections/amazon.aws#560]
### Summary

The "state: list" functionality of the `ec2_vol` module is being deprecated next year, to be replaced with this `ec2_vol_info` module.

But, there is no corresponding example in the Docs to reflect this usage.

Suggested addition to doc (something like this):
```
# Gather information about all volumes related to an EC2 Instance
# register information to `volumes` variable
# Replaces functionality of `amazon.aws.ec2_vol` - `state: list`
- name: get volume(s) info from EC2 Instance
  delegate_to: localhost
  amazon.aws.ec2_vol_info:
    filters:
      attachment.instance-id: "i-000111222333"
    region: "us-east-1"
  register: volumes
```

Thanks!

### Issue Type

Documentation Report

### Component Name

amazon.aws.ec2_vol_info

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
