### ISSUE TITLE
ec2_instance wait is not working (it was working with ec2 module)

### ISSUE THREAD

**Issue by ginigangadharan** [ansible-collections/amazon.aws#564]
### Summary

Noticed that, `ec2_instance` module `wait` argument is not working. (it was working perfectly with old `ec2` module)
Now, even after I put `wait: yes`, the task will be simply completed and proceed with next task; instance creation happening in background. When I checked the output of registered variable `created_ec2`, even `instance_id`'s are not created ! ofcourse the playbook will fail as there are many tasks depending on ec2 readiness including ssh and other tasks.

### Issue Type

Bug Report

### Component Name

ec2_instance

### Ansible Version

```console
% ansible --version
ansible [core 2.11.4] 
  config file = /Users/gini/codes/ansible-real-life/Ansible-AWS-Provisioning/ansible.cfg
  configured module search path = ['/Users/gini/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/gini/python-venv/ansible210/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/gini/codes/ansible-real-life/Ansible-AWS-Provisioning/collections
  executable location = /Users/gini/python-venv/ansible210/bin/ansible
  python version = 3.9.7 (default, Oct 13 2021, 06:45:31) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

### Collection Versions

```console 
% ansible-galaxy collection list                     

# /Users/gini/codes/ansible-real-life/Ansible-AWS-Provisioning/collections/ansible_collections
Collection        Version
----------------- -------
amazon.aws        2.0.0  
community.general 4.0.1  
```

### AWS SDK versions

```console (paste below)
% pip show boto boto3 botocore
Name: boto
Version: 2.49.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /Users/gini/python-venv/ansible210/lib/python3.9/site-packages
Requires: 
Required-by: 
---
Name: boto3
Version: 1.20.3
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /Users/gini/python-venv/ansible210/lib/python3.9/site-packages
Requires: botocore, jmespath, s3transfer
Required-by: 
---
Name: botocore
Version: 1.23.3
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /Users/gini/python-venv/ansible210/lib/python3.9/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: boto3, s3transfer
```

### Configuration

```console 
% ansible-config dump --only-changed
COLLECTIONS_PATHS(/Users/gini/codes/ansible-real-life/Ansible-AWS-Provisioning/ansible.cfg) = ['/Users/gini/codes/ansible
DEFAULT_HOST_LIST(/Users/gini/codes/ansible-real-life/Ansible-AWS-Provisioning/ansible.cfg) = ['/Users/gini/codes/ansible
DEFAULT_ROLES_PATH(/Users/gini/codes/ansible-real-life/Ansible-AWS-Provisioning/ansible.cfg) = ['/Users/gini/codes/ansible

```

### OS / Environment

MacOS with Python venv

### Steps to Reproduce

```yaml
- name: Launching EC2 instances
  amazon.aws.ec2_instance:
    profile: "{{ aws_boto_profile }}"
    key_name: "{{ aws_demo_key }}"
    security_group: "{{ aws_security_group }}"
    instance_type: "{{ item.value.instance_type }}"
    image_id: "{{ aws_ami_id }}" 
    wait: yes
    #wait_timeout: 500
    region: "{{ aws_region }}"
    tags:
       Name: "{{ item.value.name }}"
    detailed_monitoring: no
    vpc_subnet_id: "{{ vpc_subnet_list | random }}"
    network:
      assign_public_ip: yes
  loop: "{{ lookup('dict', ec2_new_list, wantlist=True) }}"
  register: created_ec2
```

### Expected Results

Expecting `ec2_instance` module to wait for the instances to be created and and proceed with next task.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
