### ISSUE TITLE
Bucket name validation is too eager and should be skippable

### ISSUE THREAD

**Issue by href** [ansible-collections/amazon.aws#593]
### Summary

With the implementation of https://github.com/ansible-collections/amazon.aws/pull/341 all bucket names must adhere to Amazon S3's naming rules. While those rules are generally followed by alternative S3 implementations, they are not a given and can sometimes be disabled (at least in the case of Ceph):

> The above constraints are relaxed if the option ‘rgw_relaxed_s3_bucket_names’ is set to true except that the bucket names must still be unique, cannot be formatted as IP address and can contain letters, numbers, periods, dashes and underscores for up to 255 characters long.

https://docs.ceph.com/en/latest/radosgw/s3/bucketops/

Furthermore, the way this works is that the bucket name is checked with every `s3_bucket` operation. So those rules don't just apply to creating new buckets, but they apply to a simple `--check --diff` run as well. At the very least, this is too eager in my estimation. If at all those rules should be applied, it should happen only when necessary.

I would like to change this in one of two ways:

1. Add an option to skip validation that is off by default (e.g. `validate_bucket_names: no (default yes)`).
2. A more fine-grained implementation that only checks the bucket name before creating a bucket, not when updating/reading it.

Those approaches could of course be combined. I'm happy to provide a pull request myself, if there are no objections to my proposal.

### Issue Type

Feature Idea

### Component Name

s3_bucket

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jillr** [comment]
Hi @href, thanks for reporting this.  If you would like to propose a PR that adds the necessary conditional handling we would definitely consider it.  We do not have a Ceph cluster (or any other non-AWS S3 implementations) available to us though for development and testing.

**Comment by href** [comment]
I implemented it by simply adding the ability to skip the check. I decided against anything smarter, because this approach has the advantage that errors bubble up early and independent of state.

That means people affected by this validation being too strict can just disable it in their playbooks, and a `--check` run alone should show if that fixes their issues.

I tested this locally with the following playbook:

```yaml
#!/usr/bin/env ansible-playbook
- name: Test bucket name validation
  hosts: localhost

  module_defaults:
    amazon.aws.s3_bucket:
      validate_bucket_name: no
      s3_url: https://objects.lpg.cloudscale.ch
    amazon.aws.aws_s3:
      validate_bucket_name: no
      s3_url: https://objects.lpg.cloudscale.ch

  tasks:
    - name: "Create bucket"
      amazon.aws.s3_bucket:
        name: foo

    - name: "Store file"
      amazon.aws.aws_s3:
        bucket: foo
        object: /bar
        content: "baz"
        mode: put
```

My employer supports bucket names shorter than 4 characters, which Amazon does not allow.
