### ISSUE TITLE
Allow to declare group variables in dynamic inventory

### ISSUE THREAD

**Issue by sebastianmacarescu** [ansible-collections/amazon.aws#620]
### Summary

Basically this feature: https://github.com/ansible/ansible/issues/66913
Any workarounds to setup `ansible_group_priority` for the groups created by this inventory plugin?

### Issue Type

Feature Idea

### Component Name

aws_ec2 inventory plugin

### Additional Information

Example
```yaml (paste below)
groups:
  a_group: tags.CustomTag == "foo"
  b_group: tags.CustomTag == "bar"

group_vars:
  a_group:
    ansible_group_priority: 10
    custom_variable: "hello world"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
