### ISSUE TITLE
ec2_group: Add `state: [present/absent]` for individual group rules

### ISSUE THREAD

**Issue by LawrenceWarren** [ansible-collections/amazon.aws#629]
## Current situation
I am using Terraform to deploy an EMR cluster and related configuration, and then [provisioning Ansible from Terraform](https://github.com/cloudposse/terraform-null-ansible) to configure Kylin on this EMR cluster.

Now, part of my companies infrastructure requires us to add the EMR security group as an ingress rule to our MSK security group, so that Kylin can talk to Kafka. The MSK security group already exists, and has several other ingress rules from other services already added to it. Adding the ingress rule is currently done manually.

I have configured our Ansible playbook to add an ingress rule to the MSK security group, for the newly deployed EMR cluster:
```yaml
name: Add EMR security group to MSK as an ingress rule
amazon.aws.ec2_group:
  name: "msk_sg_name"
  validate_certs: true
  purge_rules: false
  purge_rules_egress: false
  purge_tags: false
  rules:
   -  group_name: "emr_sg_name"
      ports:
        - 12345
        - 54321
      proto: tcp
      rule_desc: "Rule created by Ansible from terraform_module_name"
  rules_egress: [] 
```
 **Great!** This does exactly what is needed - creates an ingress rule.

## The problem

However, our EMR SG name changes every deployment. We don't often cycle Kylin, but what this will result in is that every time the playbook is rerun, we will _gain_ an additional ingress rule, without tidying up the old ones.

## Feature request

In the same way that the security group itself has a `state: [present/absent]`option, which allows you to create or delete an entire security group, add this on a per-rule basis, like as follows:

```yaml
name: Add new EMR security group to MSK as an ingress rule, delete old ingress rule
amazon.aws.ec2_group:
  name: "msk_sg_name"
  validate_certs: true
  purge_rules: false
  purge_rules_egress: false
  purge_tags: false
  rules:
   # Delete old rule
   -  group_name: "old_emr_sg_name"
      state: absent
   # Create new rule
   -  group_name: "new_emr_sg_name"
      ports:
        - 12345
        - 54321
      proto: tcp
      rule_desc: "Rule created by Ansible from terraform_module_name"
     state: present
  rules_egress: [] 
```

This would allow us to tidy up our security group rules as we continue to update and redepoy our Kylin stack.

### Issue Type

Feature Idea

### Component Name

ec2_group

### Additional Information

As provided in the body of the issue, here is example code for how this new feature request might be used.

```yaml
name: Add new EMR security group to MSK as an ingress rule, delete old ingress rule
amazon.aws.ec2_group:
  name: "msk_sg_name"
  validate_certs: true
  purge_rules: false
  purge_rules_egress: false
  purge_tags: false
  rules:
   # Delete old rule
   -  group_name: "old_emr_sg_name"
      state: absent
   # Create new rule
   -  group_name: "new_emr_sg_name"
      ports:
        - 12345
        - 54321
      proto: tcp
      rule_desc: "Rule created by Ansible from terraform_module_name"
     state: present
  rules_egress: [] 
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
