### ISSUE TITLE
ec2_group - Add support for AWS Prefix Lists

### ISSUE THREAD

**Issue by noahbailey** [ansible-collections/amazon.aws#66]
Original issue from the main Ansible repository: [67311](https://github.com/ansible/ansible/issues/67311)

##### SUMMARY

Many Amazon VPC networks use Endpoints (most commonly for S3 to save $$) to route traffic out of private network zones. 

Creating egress groups and network acls to restrict outbound traffic is generally considered a good security measure (albeit severe). So, with restricted subnets we need an easy way to add prefix lists so that restricted subnets can access S3.

It does appear that boto3 [supports this](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.authorize_security_group_egress) with the `PrefixListIds` parameter for IpPermissions, so the underlying infrastructure is already there. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
* ec2 module
* ec2_group

##### ADDITIONAL INFORMATION

An example, the structure returned by the AWS Cli tool when querying S3 endpoints in the US-EAST-1 retion: 
```json
{
    "PrefixLists": [
        {
            "PrefixListId": "pl-63a5400a",
            "Cidrs": [
                "54.231.0.0/17",
                "52.216.0.0/15",
                "3.5.16.0/21",
                "3.5.0.0/20"
            ],
            "PrefixListName": "com.amazonaws.us-east-1.s3"
        }
    ]
}
```

The important part being the `PrefixListId` value. 

A task using this feature could look like this: 

```yaml
  - name: Restrict Internet traffic 
    ec2_group: 
      name: appserver_restricted
      description: limited internet access 
      vpc_id: vpc-aaaa
      purge_rules: no 
      rules_egress: 
        - proto: all 
          cidr_ip: 10.x.0.0/16
          rule_desc: Permit traffic only to intranet 
        - proto: tcp 
          prefix_list_ids: "pl-aaaaaa"
          rule_desc: Permit access to S3 
          ports: 
            - 443 
.....
```

Thanks!
