### ISSUE TITLE
Set permission when downloading object

### ISSUE THREAD

**Issue by jlosito** [ansible-collections/amazon.aws#761]
### Summary

It would be nice if I could download an object from S3 using the `amazon.aws.aws_s3` module and set the owner, group, and permissions of the object once its been downloaded onto a VM at the same time.

There are scenarios where I have to download something from S3 which an application requires. The application is running under a specific service account, thus requiring the object to be set with an associated set of permissions for the related service account.

The issue I have is when the `amazon.aws.aws_s3` module pulls the object from S3 onto the VM, the module sets the permissions of the file to something the application does not enjoy. This causes me to have to follow up with an additional task to set the permissions properly, for instance the `ansible.builtin.file` module. Furthermore, if I were to run the same playbook again, I would assume it to be idempotent, without any changes, but due to the fact the `amazon.aws.aws_s3` module setting the permissions of the file back to something I do not want, the `ansible.builtin.file` module will have to again set it properly.

### Issue Type

Feature Idea

### Component Name

aws_s3

### Additional Information

```yaml (paste below)
- name: Download my object
  amazon.aws.aws_s3:
    bucket: "my_bucket"
    object: "my_object"
    dest: "/tmp/my_object"
    mode: get
    owner: my_linux_user
    group: my_linux_group
    perm: 0640
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
