### ISSUE TITLE
device_mapping in amazon.aws.ec2_ami requires root_device

### ISSUE THREAD

**Issue by JonasEckhardt** [ansible-collections/amazon.aws#770]
### Summary

From reading https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_ami_module.html I tried creating a minimal working example to create a AMI with an encrypted snapshot:
```
- name: basic AMI Creation, without waiting
  amazon.aws.ec2_ami:
    instance_id: "{{ instance_id }}"
    wait: no
    name: "{{ ami_name }}"
    device_mapping:
      - device_name: /dev/xvda
        encrypted: true
```

Even though specified in the code the snapshot is not encrypted. It was possible to solve this by adding the `root_device_name`:
```
- name: basic AMI Creation, without waiting
  amazon.aws.ec2_ami:
    instance_id: "{{ instance_id }}"
    wait: no
    name: "{{ ami_name }}"
    root_device_name: /dev/xvda
    device_mapping:
      - device_name: /dev/xvda
        encrypted: true
    tags:
      Name: "{{ ami_name }}"
```
To me it would be helpful to add to the description of `device_mapping` the hint that the `root_device_name` needs to be specified. Otherwise the device_mapping will be ignored.

HINT: I tested the same code also with `delete_on_termination` and it resulted in the same behaviour.

### Issue Type

Documentation Report

### Component Name

ec2_ami

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### Configuration

Empty

### OS / Environment

Amazonlinux 2

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
