### ISSUE TITLE
Composing inventory_hostname manually

### ISSUE THREAD

**Issue by aobertyshev** [ansible-collections/amazon.aws#814]
### Summary

Here is my current config:
```yaml
---
plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
hostnames:
  - tag:Name
compose:
  ansible_host: private_ip_address
```

Executing it sets inventory_hostname variable(s) to the "Name" tag value. However, I would like to know whether it's possible to create a completely custom inventory_hostname, as I haven't found a clear way to do it by searching through the docs (as far as I understood it's only allowed to use the values from [here](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html#options) which doesn't suit my case).

I have an AWS cloud and an Azure cloud, which serves as a mirror of the AWS cloud. The VMs on both clouds are named similarly (e.g. "prometheus"). I would like to refer to these VMs as 'aws-prometheus' and 'azu-prometheus'. The [azure_rm plugin](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html#parameter-hostnames) allows creating custom inventory_hostname:

```yaml
hostnames:
  - "'azu-' + name"
```
, where "name" is just a key in the object returned by the API (like 'private_ip_address' for AWS). This way, I can refer to Azure VMs with 'azu-' prefix.

I would like to know whether it's possible to do the same with the aws_ec2 plugin. I've played around with different combinations and values for 'hostnames' but found myself limited with the values allowed by AWS.

This doesn't work because "aws-" is not a recognized value from [here](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html#options):
```yaml
---
plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
hostnames:
  - name: "tag:Name"
    prefix: "aws-"
compose:
  ansible_host: private_ip_address
```

Thank you in advance.

### Issue Type

Feature Idea

### Component Name

amazon.aws.aws_ec2

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jatorcasso** [comment]
Hi @aobertyshev ,

Thanks for taking the time to raise this issue. #826 should fix this.

**Comment by aobertyshev** [comment]
Thank you, frankly I expected it was me not being able to do this properly rather than this feature missing :)

I had a quick look through the PR, do I understand correctly that a new config would look like this:
```yaml
---
plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
hostnames:
  - name: "tag:Name"
    prefix: "aws-"
compose:
  ansible_host: private_ip_address
```
or like this:
```yaml
---
plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
hostnames:
  - name: "tag:Name"
    separator: "-"
    prefix: "aws"
compose:
  ansible_host: private_ip_address
```
E.g. I have a machine on AWS with the tag "Name" of value "prometheus".
Would both of these configs make it possible to refer to this VM as "aws-prometheus" in the playbooks?

Thank you in advance.

**Comment by jatorcasso** [comment]
> Thank you, frankly I expected it was me not being able to do this properly rather than this feature missing :)
> 
> I had a quick look through the PR, do I understand correctly that a new config would look like this:
> 
> ```yaml
> ---
> plugin: amazon.aws.aws_ec2
> regions:
>   - eu-central-1
> hostnames:
>   - name: "tag:Name"
>     prefix: "aws-"
> compose:
>   ansible_host: private_ip_address
> ```
> 
> or like this:
> 
> ```yaml
> ---
> plugin: amazon.aws.aws_ec2
> regions:
>   - eu-central-1
> hostnames:
>   - name: "tag:Name"
>     separator: "-"
>     prefix: "aws"
> compose:
>   ansible_host: private_ip_address
> ```
> 
> E.g. I have a machine on AWS with the tag "Name" of value "prometheus". Would both of these configs make it possible to refer to this VM as "aws-prometheus" in the playbooks?
> 
> Thank you in advance.

Just double checked and you should be able to use the `hostvars_prefix`! So, that would look like:

**Comment by aobertyshev** [comment]
Thank you for the fast reply.

`hostvars_prefix` is, per documentation, `The prefix for host variables names coming from AWS.`
So, having the following config:
```yaml
---
plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
hostvars_prefix: "aws-"
hostnames:
  - tag:Name
```
and executing the following command:
`ansible-inventory -i inventory/aws_ec2.yml --list`
returned:
![image](https://user-images.githubusercontent.com/4324562/170028441-9b73656a-22e6-4b50-83b6-27da6a6e3332.png)

While it does what is stated in the documentation, it doesn't alter the hostname itself (and, of course, I'd like to keep the original var names). Thus, eagerly waiting for this PR to get merged :)
