### ISSUE TITLE
Create module for managing Amazon Data Lifecycle Manager policies

### ISSUE THREAD

**Issue by jsalatiel** [ansible-collections/amazon.aws#879]
### Summary

Would it be possible to create a module to manage Amazon Data Lifecycle Manager policies?

### Issue Type

Feature Idea

### Component Name

amazon.aws.ec2_dlm

### Additional Information

```yaml (paste below)
   - name: Create data lifecyle policy
      amazon.aws.ec2_dlm:
        state: present
        tags: '{{ item.tags }}'
        region: '{{ region }}'
        name: backupByTag
        schedule: */12
        type: ebs_snapshot
        target_type: volume
        target_tags:
        - backup: true


 
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
