### ISSUE TITLE
Boot mode and TPM support for AMI creation

### ISSUE THREAD

**Issue by avery-blanchard** [ansible-collections/amazon.aws#944]
### Summary

I would like to use ansible to create an AMI with UEFI secure boot and TPM support. In the [ec2_ami module](https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_ami_module.html#ansible-collections-amazon-aws-ec2-ami-module), there are currently no parameters to do so. As UEFI and TPM support for Linux AMIs is new for AWS, I think it would be a useful new feature to add parameters for boot mode and tpm support. [Amazon EC2 Now Supports NitroTPM and UEFI Secure Boot](https://aws.amazon.com/blogs/aws/amazon-ec2-now-supports-nitrotpm-and-uefi-secure-boot/)

### Issue Type

Feature Idea

### Component Name

ec2_ami

### Additional Information

```yaml (paste below)
 - name: Create AMI
    amazon.aws.ec2_ami:
         name: test
         state: present
         architecture: x86_64
         virtualization_type: hvm
         root_device_name: /dev/sda1
         device_mapping:
                 - device_name: /dev/sda1
                    snapshot_id: "{{ snapshot_id }}"
          wait: yes
          region: us-east-1
          boot_mode: uefi
          uefi_data: data_file.bin
          tpm_support: v2.0  
                                       
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
