### ISSUE TITLE
ec2_instance enable hibernate option for instance_initiated_shutdown_behavior

### ISSUE THREAD

**Issue by RonneGisun** [ansible-collections/amazon.aws#969]
### Summary

I am trying to launch new EC2 instances with the 'stop hibernate' option enabled, as per options available in AWS Console.
https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-ec2-hibernation-now-available-on-windows/

### Issue Type

Feature Idea

### Component Name

ec2_instance

### Additional Information

```yaml (paste below)
- name: start an instance with a hibernate_options
  amazon.aws.ec2_instance:
    name: "public-cpuoption-instance"
    vpc_subnet_id: subnet-5ca1ab1e
    tags:
      Environment: Testing
    instance_type: c4.large
    volumes:
    - device_name: /dev/sda1
      ebs:
        delete_on_termination: true
    cpu_options:
        core_count: 1
        threads_per_core: 1
    instance_initiated_shutdown_behavior: "stop_hibernate"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
